// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           AgentType              `protobuf:"varint,2,opt,name=type,proto3,enum=swarm.v1.AgentType" json:"type,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	SystemPrompt   string                 `protobuf:"bytes,5,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Skills         []string               `protobuf:"bytes,6,rep,name=skills,proto3" json:"skills,omitempty"`
	MaxConcurrent  int32                  `protobuf:"varint,7,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	TimeoutMs      int64                  `protobuf:"varint,8,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,9,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	ResourceLimits *ResourceLimits        `protobuf:"bytes,10,opt,name=resource_limits,json=resourceLimits,proto3" json:"resource_limits,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateAgentRequest) GetType() AgentType {
	if x != nil {
		return x.Type
	}
	return AgentType_AGENT_TYPE_UNSPECIFIED
}

func (x *CreateAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAgentRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateAgentRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *CreateAgentRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CreateAgentRequest) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *CreateAgentRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *CreateAgentRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *CreateAgentRequest) GetResourceLimits() *ResourceLimits {
	if x != nil {
		return x.ResourceLimits
	}
	return nil
}

type CreateAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentResponse) Reset() {
	*x = CreateAgentResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentResponse) ProtoMessage() {}

func (x *CreateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          AgentType              `protobuf:"varint,1,opt,name=type,proto3,enum=swarm.v1.AgentType" json:"type,omitempty"`
	Status        AgentStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=swarm.v1.AgentStatus" json:"status,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ListAgentsRequest) GetType() AgentType {
	if x != nil {
		return x.Type
	}
	return AgentType_AGENT_TYPE_UNSPECIFIED
}

func (x *ListAgentsRequest) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *ListAgentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAgentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAgentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Skills        []string               `protobuf:"bytes,4,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentRequest) Reset() {
	*x = UpdateAgentRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRequest) ProtoMessage() {}

func (x *UpdateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAgentRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *UpdateAgentRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

type UpdateAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentResponse) Reset() {
	*x = UpdateAgentResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentResponse) ProtoMessage() {}

func (x *UpdateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentResponse.ProtoReflect.Descriptor instead.
func (*UpdateAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type DeleteAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StartAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAgentRequest) Reset() {
	*x = StartAgentRequest{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAgentRequest) ProtoMessage() {}

func (x *StartAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAgentRequest.ProtoReflect.Descriptor instead.
func (*StartAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *StartAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StartAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAgentResponse) Reset() {
	*x = StartAgentResponse{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAgentResponse) ProtoMessage() {}

func (x *StartAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAgentResponse.ProtoReflect.Descriptor instead.
func (*StartAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *StartAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type StopAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAgentRequest) Reset() {
	*x = StopAgentRequest{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAgentRequest) ProtoMessage() {}

func (x *StopAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAgentRequest.ProtoReflect.Descriptor instead.
func (*StopAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *StopAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAgentResponse) Reset() {
	*x = StopAgentResponse{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAgentResponse) ProtoMessage() {}

func (x *StopAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAgentResponse.ProtoReflect.Descriptor instead.
func (*StopAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *StopAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type PauseAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseAgentRequest) Reset() {
	*x = PauseAgentRequest{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseAgentRequest) ProtoMessage() {}

func (x *PauseAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseAgentRequest.ProtoReflect.Descriptor instead.
func (*PauseAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *PauseAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PauseAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseAgentResponse) Reset() {
	*x = PauseAgentResponse{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseAgentResponse) ProtoMessage() {}

func (x *PauseAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseAgentResponse.ProtoReflect.Descriptor instead.
func (*PauseAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *PauseAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type ResumeAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeAgentRequest) Reset() {
	*x = ResumeAgentRequest{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeAgentRequest) ProtoMessage() {}

func (x *ResumeAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeAgentRequest.ProtoReflect.Descriptor instead.
func (*ResumeAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ResumeAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResumeAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeAgentResponse) Reset() {
	*x = ResumeAgentResponse{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeAgentResponse) ProtoMessage() {}

func (x *ResumeAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeAgentResponse.ProtoReflect.Descriptor instead.
func (*ResumeAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ResumeAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type GetAgentMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentMetricsRequest) Reset() {
	*x = GetAgentMetricsRequest{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentMetricsRequest) ProtoMessage() {}

func (x *GetAgentMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetAgentMetricsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *GetAgentMetricsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAgentMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *AgentMetrics          `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentMetricsResponse) Reset() {
	*x = GetAgentMetricsResponse{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentMetricsResponse) ProtoMessage() {}

func (x *GetAgentMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetAgentMetricsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *GetAgentMetricsResponse) GetMetrics() *AgentMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GetAgentHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentHealthRequest) Reset() {
	*x = GetAgentHealthRequest{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentHealthRequest) ProtoMessage() {}

func (x *GetAgentHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentHealthRequest.ProtoReflect.Descriptor instead.
func (*GetAgentHealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *GetAgentHealthRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAgentHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *AgentHealth           `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentHealthResponse) Reset() {
	*x = GetAgentHealthResponse{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentHealthResponse) ProtoMessage() {}

func (x *GetAgentHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentHealthResponse.ProtoReflect.Descriptor instead.
func (*GetAgentHealthResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *GetAgentHealthResponse) GetHealth() *AgentHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

type StreamAgentMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	IntervalMs    int64                  `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAgentMetricsRequest) Reset() {
	*x = StreamAgentMetricsRequest{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAgentMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAgentMetricsRequest) ProtoMessage() {}

func (x *StreamAgentMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAgentMetricsRequest.ProtoReflect.Descriptor instead.
func (*StreamAgentMetricsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *StreamAgentMetricsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StreamAgentMetricsRequest) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type AgentMetricUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Metrics       *AgentMetrics          `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMetricUpdate) Reset() {
	*x = AgentMetricUpdate{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetricUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetricUpdate) ProtoMessage() {}

func (x *AgentMetricUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetricUpdate.ProtoReflect.Descriptor instead.
func (*AgentMetricUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *AgentMetricUpdate) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMetricUpdate) GetMetrics() *AgentMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *AgentMetricUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StreamAgentHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	IntervalMs    int64                  `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAgentHealthRequest) Reset() {
	*x = StreamAgentHealthRequest{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAgentHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAgentHealthRequest) ProtoMessage() {}

func (x *StreamAgentHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAgentHealthRequest.ProtoReflect.Descriptor instead.
func (*StreamAgentHealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *StreamAgentHealthRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StreamAgentHealthRequest) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type AgentHealthUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Health        *AgentHealth           `protobuf:"bytes,2,opt,name=health,proto3" json:"health,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHealthUpdate) Reset() {
	*x = AgentHealthUpdate{}
	mi := &file_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHealthUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHealthUpdate) ProtoMessage() {}

func (x *AgentHealthUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHealthUpdate.ProtoReflect.Descriptor instead.
func (*AgentHealthUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

func (x *AgentHealthUpdate) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentHealthUpdate) GetHealth() *AgentHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *AgentHealthUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          AgentType              `protobuf:"varint,2,opt,name=type,proto3,enum=swarm.v1.AgentType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Status        AgentStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=swarm.v1.AgentStatus" json:"status,omitempty"`
	Skills        []string               `protobuf:"bytes,6,rep,name=skills,proto3" json:"skills,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{25}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetType() AgentType {
	if x != nil {
		return x.Type
	}
	return AgentType_AGENT_TYPE_UNSPECIFIED
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Agent) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *Agent) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Agent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Agent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Agent) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

type ResourceLimits struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MaxMemoryMb      int32                  `protobuf:"varint,1,opt,name=max_memory_mb,json=maxMemoryMb,proto3" json:"max_memory_mb,omitempty"`
	MaxCpuPercent    int32                  `protobuf:"varint,2,opt,name=max_cpu_percent,json=maxCpuPercent,proto3" json:"max_cpu_percent,omitempty"`
	MaxTokensPerTask int32                  `protobuf:"varint,3,opt,name=max_tokens_per_task,json=maxTokensPerTask,proto3" json:"max_tokens_per_task,omitempty"`
	MaxTasksPerHour  int32                  `protobuf:"varint,4,opt,name=max_tasks_per_hour,json=maxTasksPerHour,proto3" json:"max_tasks_per_hour,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{26}
}

func (x *ResourceLimits) GetMaxMemoryMb() int32 {
	if x != nil {
		return x.MaxMemoryMb
	}
	return 0
}

func (x *ResourceLimits) GetMaxCpuPercent() int32 {
	if x != nil {
		return x.MaxCpuPercent
	}
	return 0
}

func (x *ResourceLimits) GetMaxTokensPerTask() int32 {
	if x != nil {
		return x.MaxTokensPerTask
	}
	return 0
}

func (x *ResourceLimits) GetMaxTasksPerHour() int32 {
	if x != nil {
		return x.MaxTasksPerHour
	}
	return 0
}

type AgentMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TasksCompleted  int64                  `protobuf:"varint,1,opt,name=tasks_completed,json=tasksCompleted,proto3" json:"tasks_completed,omitempty"`
	TasksFailed     int64                  `protobuf:"varint,2,opt,name=tasks_failed,json=tasksFailed,proto3" json:"tasks_failed,omitempty"`
	AvgDurationMs   int64                  `protobuf:"varint,3,opt,name=avg_duration_ms,json=avgDurationMs,proto3" json:"avg_duration_ms,omitempty"`
	TotalTokensUsed int64                  `protobuf:"varint,4,opt,name=total_tokens_used,json=totalTokensUsed,proto3" json:"total_tokens_used,omitempty"`
	TotalCost       float64                `protobuf:"fixed64,5,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	LastActivity    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentMetrics) Reset() {
	*x = AgentMetrics{}
	mi := &file_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetrics) ProtoMessage() {}

func (x *AgentMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetrics.ProtoReflect.Descriptor instead.
func (*AgentMetrics) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{27}
}

func (x *AgentMetrics) GetTasksCompleted() int64 {
	if x != nil {
		return x.TasksCompleted
	}
	return 0
}

func (x *AgentMetrics) GetTasksFailed() int64 {
	if x != nil {
		return x.TasksFailed
	}
	return 0
}

func (x *AgentMetrics) GetAvgDurationMs() int64 {
	if x != nil {
		return x.AvgDurationMs
	}
	return 0
}

func (x *AgentMetrics) GetTotalTokensUsed() int64 {
	if x != nil {
		return x.TotalTokensUsed
	}
	return 0
}

func (x *AgentMetrics) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *AgentMetrics) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

type AgentHealth struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	LastHeartbeat  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	CpuUsage       float64                `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsageMb  int32                  `protobuf:"varint,4,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`
	ActiveRequests int32                  `protobuf:"varint,5,opt,name=active_requests,json=activeRequests,proto3" json:"active_requests,omitempty"`
	ErrorCount     int32                  `protobuf:"varint,6,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentHealth) Reset() {
	*x = AgentHealth{}
	mi := &file_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHealth) ProtoMessage() {}

func (x *AgentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHealth.ProtoReflect.Descriptor instead.
func (*AgentHealth) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{28}
}

func (x *AgentHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentHealth) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *AgentHealth) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *AgentHealth) GetMemoryUsageMb() int32 {
	if x != nil {
		return x.MemoryUsageMb
	}
	return 0
}

func (x *AgentHealth) GetActiveRequests() int32 {
	if x != nil {
		return x.ActiveRequests
	}
	return 0
}

func (x *AgentHealth) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\bswarm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\fcommon.proto\x1a\n" +
	"task.proto\"\xde\x02\n" +
	"\x12CreateAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.swarm.v1.AgentTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12#\n" +
	"\rsystem_prompt\x18\x05 \x01(\tR\fsystemPrompt\x12\x16\n" +
	"\x06skills\x18\x06 \x03(\tR\x06skills\x12%\n" +
	"\x0emax_concurrent\x18\a \x01(\x05R\rmaxConcurrent\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\b \x01(\x03R\ttimeoutMs\x12\x1f\n" +
	"\vmax_retries\x18\t \x01(\x05R\n" +
	"maxRetries\x12A\n" +
	"\x0fresource_limits\x18\n" +
	" \x01(\v2\x18.swarm.v1.ResourceLimitsR\x0eresourceLimits\"<\n" +
	"\x13CreateAgentResponse\x12%\n" +
	"\x05agent\x18\x01 \x01(\v2\x0f.swarm.v1.AgentR\x05agent\"!\n" +
	"\x0fGetAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x10GetAgentResponse\x12%\n" +
	"\x05agent\x18\x01 \x01(\v2\x0f.swarm.v1.AgentR\x05agent\"\xa7\x01\n" +
	"\x11ListAgentsRequest\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.swarm.v1.AgentTypeR\x04type\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.swarm.v1.AgentStatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x86\x01\n" +
	"\x12ListAgentsResponse\x12'\n" +
	"\x06agents\x18\x01 \x03(\v2\x0f.swarm.v1.AgentR\x06agents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"u\n" +
	"\x12UpdateAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12\x16\n" +
	"\x06skills\x18\x04 \x03(\tR\x06skills\"<\n" +
	"\x13UpdateAgentResponse\x12%\n" +
	"\x05agent\x18\x01 \x01(\v2\x0f.swarm.v1.AgentR\x05agent\"$\n" +
	"\x12DeleteAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11StartAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x12StartAgentResponse\x12%\n" +
	"\x05agent\x18\x01 \x01(\v2\x0f.swarm.v1.AgentR\x05agent\"\"\n" +
	"\x10StopAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x11StopAgentResponse\x12%\n" +
	"\x05agent\x18\x01 \x01(\v2\x0f.swarm.v1.AgentR\x05agent\"#\n" +
	"\x11PauseAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x12PauseAgentResponse\x12%\n" +
	"\x05agent\x18\x01 \x01(\v2\x0f.swarm.v1.AgentR\x05agent\"$\n" +
	"\x12ResumeAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x13ResumeAgentResponse\x12%\n" +
	"\x05agent\x18\x01 \x01(\v2\x0f.swarm.v1.AgentR\x05agent\"(\n" +
	"\x16GetAgentMetricsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x17GetAgentMetricsResponse\x120\n" +
	"\ametrics\x18\x01 \x01(\v2\x16.swarm.v1.AgentMetricsR\ametrics\"'\n" +
	"\x15GetAgentHealthRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x16GetAgentHealthResponse\x12-\n" +
	"\x06health\x18\x01 \x01(\v2\x15.swarm.v1.AgentHealthR\x06health\"W\n" +
	"\x19StreamAgentMetricsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\x03R\n" +
	"intervalMs\"\x9a\x01\n" +
	"\x11AgentMetricUpdate\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x120\n" +
	"\ametrics\x18\x02 \x01(\v2\x16.swarm.v1.AgentMetricsR\ametrics\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"V\n" +
	"\x18StreamAgentHealthRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\x03R\n" +
	"intervalMs\"\x97\x01\n" +
	"\x11AgentHealthUpdate\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12-\n" +
	"\x06health\x18\x02 \x01(\v2\x15.swarm.v1.AgentHealthR\x06health\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xea\x02\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.swarm.v1.AgentTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.swarm.v1.AgentStatusR\x06status\x12\x16\n" +
	"\x06skills\x18\x06 \x03(\tR\x06skills\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12A\n" +
	"\x0elast_heartbeat\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\"\xb8\x01\n" +
	"\x0eResourceLimits\x12\"\n" +
	"\rmax_memory_mb\x18\x01 \x01(\x05R\vmaxMemoryMb\x12&\n" +
	"\x0fmax_cpu_percent\x18\x02 \x01(\x05R\rmaxCpuPercent\x12-\n" +
	"\x13max_tokens_per_task\x18\x03 \x01(\x05R\x10maxTokensPerTask\x12+\n" +
	"\x12max_tasks_per_hour\x18\x04 \x01(\x05R\x0fmaxTasksPerHour\"\x8e\x02\n" +
	"\fAgentMetrics\x12'\n" +
	"\x0ftasks_completed\x18\x01 \x01(\x03R\x0etasksCompleted\x12!\n" +
	"\ftasks_failed\x18\x02 \x01(\x03R\vtasksFailed\x12&\n" +
	"\x0favg_duration_ms\x18\x03 \x01(\x03R\ravgDurationMs\x12*\n" +
	"\x11total_tokens_used\x18\x04 \x01(\x03R\x0ftotalTokensUsed\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x05 \x01(\x01R\ttotalCost\x12?\n" +
	"\rlast_activity\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\"\xf7\x01\n" +
	"\vAgentHealth\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12A\n" +
	"\x0elast_heartbeat\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12&\n" +
	"\x0fmemory_usage_mb\x18\x04 \x01(\x05R\rmemoryUsageMb\x12'\n" +
	"\x0factive_requests\x18\x05 \x01(\x05R\x0eactiveRequests\x12\x1f\n" +
	"\verror_count\x18\x06 \x01(\x05R\n" +
	"errorCount2\xc6\b\n" +
	"\fAgentService\x12J\n" +
	"\vCreateAgent\x12\x1c.swarm.v1.CreateAgentRequest\x1a\x1d.swarm.v1.CreateAgentResponse\x12A\n" +
	"\bGetAgent\x12\x19.swarm.v1.GetAgentRequest\x1a\x1a.swarm.v1.GetAgentResponse\x12G\n" +
	"\n" +
	"ListAgents\x12\x1b.swarm.v1.ListAgentsRequest\x1a\x1c.swarm.v1.ListAgentsResponse\x12J\n" +
	"\vUpdateAgent\x12\x1c.swarm.v1.UpdateAgentRequest\x1a\x1d.swarm.v1.UpdateAgentResponse\x12C\n" +
	"\vDeleteAgent\x12\x1c.swarm.v1.DeleteAgentRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\n" +
	"StartAgent\x12\x1b.swarm.v1.StartAgentRequest\x1a\x1c.swarm.v1.StartAgentResponse\x12D\n" +
	"\tStopAgent\x12\x1a.swarm.v1.StopAgentRequest\x1a\x1b.swarm.v1.StopAgentResponse\x12G\n" +
	"\n" +
	"PauseAgent\x12\x1b.swarm.v1.PauseAgentRequest\x1a\x1c.swarm.v1.PauseAgentResponse\x12J\n" +
	"\vResumeAgent\x12\x1c.swarm.v1.ResumeAgentRequest\x1a\x1d.swarm.v1.ResumeAgentResponse\x12J\n" +
	"\vExecuteTask\x12\x1c.swarm.v1.ExecuteTaskRequest\x1a\x1d.swarm.v1.ExecuteTaskResponse\x12V\n" +
	"\x0fGetAgentMetrics\x12 .swarm.v1.GetAgentMetricsRequest\x1a!.swarm.v1.GetAgentMetricsResponse\x12S\n" +
	"\x0eGetAgentHealth\x12\x1f.swarm.v1.GetAgentHealthRequest\x1a .swarm.v1.GetAgentHealthResponse\x12X\n" +
	"\x12StreamAgentMetrics\x12#.swarm.v1.StreamAgentMetricsRequest\x1a\x1b.swarm.v1.AgentMetricUpdate0\x01\x12V\n" +
	"\x11StreamAgentHealth\x12\".swarm.v1.StreamAgentHealthRequest\x1a\x1b.swarm.v1.AgentHealthUpdate0\x01B6Z4github.com/swarm-ai/swarm/internal/server/grpc/protob\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_agent_proto_goTypes = []any{
	(*CreateAgentRequest)(nil),        // 0: swarm.v1.CreateAgentRequest
	(*CreateAgentResponse)(nil),       // 1: swarm.v1.CreateAgentResponse
	(*GetAgentRequest)(nil),           // 2: swarm.v1.GetAgentRequest
	(*GetAgentResponse)(nil),          // 3: swarm.v1.GetAgentResponse
	(*ListAgentsRequest)(nil),         // 4: swarm.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),        // 5: swarm.v1.ListAgentsResponse
	(*UpdateAgentRequest)(nil),        // 6: swarm.v1.UpdateAgentRequest
	(*UpdateAgentResponse)(nil),       // 7: swarm.v1.UpdateAgentResponse
	(*DeleteAgentRequest)(nil),        // 8: swarm.v1.DeleteAgentRequest
	(*StartAgentRequest)(nil),         // 9: swarm.v1.StartAgentRequest
	(*StartAgentResponse)(nil),        // 10: swarm.v1.StartAgentResponse
	(*StopAgentRequest)(nil),          // 11: swarm.v1.StopAgentRequest
	(*StopAgentResponse)(nil),         // 12: swarm.v1.StopAgentResponse
	(*PauseAgentRequest)(nil),         // 13: swarm.v1.PauseAgentRequest
	(*PauseAgentResponse)(nil),        // 14: swarm.v1.PauseAgentResponse
	(*ResumeAgentRequest)(nil),        // 15: swarm.v1.ResumeAgentRequest
	(*ResumeAgentResponse)(nil),       // 16: swarm.v1.ResumeAgentResponse
	(*GetAgentMetricsRequest)(nil),    // 17: swarm.v1.GetAgentMetricsRequest
	(*GetAgentMetricsResponse)(nil),   // 18: swarm.v1.GetAgentMetricsResponse
	(*GetAgentHealthRequest)(nil),     // 19: swarm.v1.GetAgentHealthRequest
	(*GetAgentHealthResponse)(nil),    // 20: swarm.v1.GetAgentHealthResponse
	(*StreamAgentMetricsRequest)(nil), // 21: swarm.v1.StreamAgentMetricsRequest
	(*AgentMetricUpdate)(nil),         // 22: swarm.v1.AgentMetricUpdate
	(*StreamAgentHealthRequest)(nil),  // 23: swarm.v1.StreamAgentHealthRequest
	(*AgentHealthUpdate)(nil),         // 24: swarm.v1.AgentHealthUpdate
	(*Agent)(nil),                     // 25: swarm.v1.Agent
	(*ResourceLimits)(nil),            // 26: swarm.v1.ResourceLimits
	(*AgentMetrics)(nil),              // 27: swarm.v1.AgentMetrics
	(*AgentHealth)(nil),               // 28: swarm.v1.AgentHealth
	(AgentType)(0),                    // 29: swarm.v1.AgentType
	(AgentStatus)(0),                  // 30: swarm.v1.AgentStatus
	(*timestamppb.Timestamp)(nil),     // 31: google.protobuf.Timestamp
	(*ExecuteTaskRequest)(nil),        // 32: swarm.v1.ExecuteTaskRequest
	(*emptypb.Empty)(nil),             // 33: google.protobuf.Empty
	(*ExecuteTaskResponse)(nil),       // 34: swarm.v1.ExecuteTaskResponse
}
var file_agent_proto_depIdxs = []int32{
	29, // 0: swarm.v1.CreateAgentRequest.type:type_name -> swarm.v1.AgentType
	26, // 1: swarm.v1.CreateAgentRequest.resource_limits:type_name -> swarm.v1.ResourceLimits
	25, // 2: swarm.v1.CreateAgentResponse.agent:type_name -> swarm.v1.Agent
	25, // 3: swarm.v1.GetAgentResponse.agent:type_name -> swarm.v1.Agent
	29, // 4: swarm.v1.ListAgentsRequest.type:type_name -> swarm.v1.AgentType
	30, // 5: swarm.v1.ListAgentsRequest.status:type_name -> swarm.v1.AgentStatus
	25, // 6: swarm.v1.ListAgentsResponse.agents:type_name -> swarm.v1.Agent
	25, // 7: swarm.v1.UpdateAgentResponse.agent:type_name -> swarm.v1.Agent
	25, // 8: swarm.v1.StartAgentResponse.agent:type_name -> swarm.v1.Agent
	25, // 9: swarm.v1.StopAgentResponse.agent:type_name -> swarm.v1.Agent
	25, // 10: swarm.v1.PauseAgentResponse.agent:type_name -> swarm.v1.Agent
	25, // 11: swarm.v1.ResumeAgentResponse.agent:type_name -> swarm.v1.Agent
	27, // 12: swarm.v1.GetAgentMetricsResponse.metrics:type_name -> swarm.v1.AgentMetrics
	28, // 13: swarm.v1.GetAgentHealthResponse.health:type_name -> swarm.v1.AgentHealth
	27, // 14: swarm.v1.AgentMetricUpdate.metrics:type_name -> swarm.v1.AgentMetrics
	31, // 15: swarm.v1.AgentMetricUpdate.timestamp:type_name -> google.protobuf.Timestamp
	28, // 16: swarm.v1.AgentHealthUpdate.health:type_name -> swarm.v1.AgentHealth
	31, // 17: swarm.v1.AgentHealthUpdate.timestamp:type_name -> google.protobuf.Timestamp
	29, // 18: swarm.v1.Agent.type:type_name -> swarm.v1.AgentType
	30, // 19: swarm.v1.Agent.status:type_name -> swarm.v1.AgentStatus
	31, // 20: swarm.v1.Agent.created_at:type_name -> google.protobuf.Timestamp
	31, // 21: swarm.v1.Agent.updated_at:type_name -> google.protobuf.Timestamp
	31, // 22: swarm.v1.Agent.last_heartbeat:type_name -> google.protobuf.Timestamp
	31, // 23: swarm.v1.AgentMetrics.last_activity:type_name -> google.protobuf.Timestamp
	31, // 24: swarm.v1.AgentHealth.last_heartbeat:type_name -> google.protobuf.Timestamp
	0,  // 25: swarm.v1.AgentService.CreateAgent:input_type -> swarm.v1.CreateAgentRequest
	2,  // 26: swarm.v1.AgentService.GetAgent:input_type -> swarm.v1.GetAgentRequest
	4,  // 27: swarm.v1.AgentService.ListAgents:input_type -> swarm.v1.ListAgentsRequest
	6,  // 28: swarm.v1.AgentService.UpdateAgent:input_type -> swarm.v1.UpdateAgentRequest
	8,  // 29: swarm.v1.AgentService.DeleteAgent:input_type -> swarm.v1.DeleteAgentRequest
	9,  // 30: swarm.v1.AgentService.StartAgent:input_type -> swarm.v1.StartAgentRequest
	11, // 31: swarm.v1.AgentService.StopAgent:input_type -> swarm.v1.StopAgentRequest
	13, // 32: swarm.v1.AgentService.PauseAgent:input_type -> swarm.v1.PauseAgentRequest
	15, // 33: swarm.v1.AgentService.ResumeAgent:input_type -> swarm.v1.ResumeAgentRequest
	32, // 34: swarm.v1.AgentService.ExecuteTask:input_type -> swarm.v1.ExecuteTaskRequest
	17, // 35: swarm.v1.AgentService.GetAgentMetrics:input_type -> swarm.v1.GetAgentMetricsRequest
	19, // 36: swarm.v1.AgentService.GetAgentHealth:input_type -> swarm.v1.GetAgentHealthRequest
	21, // 37: swarm.v1.AgentService.StreamAgentMetrics:input_type -> swarm.v1.StreamAgentMetricsRequest
	23, // 38: swarm.v1.AgentService.StreamAgentHealth:input_type -> swarm.v1.StreamAgentHealthRequest
	1,  // 39: swarm.v1.AgentService.CreateAgent:output_type -> swarm.v1.CreateAgentResponse
	3,  // 40: swarm.v1.AgentService.GetAgent:output_type -> swarm.v1.GetAgentResponse
	5,  // 41: swarm.v1.AgentService.ListAgents:output_type -> swarm.v1.ListAgentsResponse
	7,  // 42: swarm.v1.AgentService.UpdateAgent:output_type -> swarm.v1.UpdateAgentResponse
	33, // 43: swarm.v1.AgentService.DeleteAgent:output_type -> google.protobuf.Empty
	10, // 44: swarm.v1.AgentService.StartAgent:output_type -> swarm.v1.StartAgentResponse
	12, // 45: swarm.v1.AgentService.StopAgent:output_type -> swarm.v1.StopAgentResponse
	14, // 46: swarm.v1.AgentService.PauseAgent:output_type -> swarm.v1.PauseAgentResponse
	16, // 47: swarm.v1.AgentService.ResumeAgent:output_type -> swarm.v1.ResumeAgentResponse
	34, // 48: swarm.v1.AgentService.ExecuteTask:output_type -> swarm.v1.ExecuteTaskResponse
	18, // 49: swarm.v1.AgentService.GetAgentMetrics:output_type -> swarm.v1.GetAgentMetricsResponse
	20, // 50: swarm.v1.AgentService.GetAgentHealth:output_type -> swarm.v1.GetAgentHealthResponse
	22, // 51: swarm.v1.AgentService.StreamAgentMetrics:output_type -> swarm.v1.AgentMetricUpdate
	24, // 52: swarm.v1.AgentService.StreamAgentHealth:output_type -> swarm.v1.AgentHealthUpdate
	39, // [39:53] is the sub-list for method output_type
	25, // [25:39] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_common_proto_init()
	file_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
