// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentType int32

const (
	AgentType_AGENT_TYPE_UNSPECIFIED AgentType = 0
	AgentType_AGENT_TYPE_ARCHITECT   AgentType = 1
	AgentType_AGENT_TYPE_CODER       AgentType = 2
	AgentType_AGENT_TYPE_TESTER      AgentType = 3
	AgentType_AGENT_TYPE_REVIEWER    AgentType = 4
	AgentType_AGENT_TYPE_RESEARCHER  AgentType = 5
	AgentType_AGENT_TYPE_COORDINATOR AgentType = 6
)

// Enum value maps for AgentType.
var (
	AgentType_name = map[int32]string{
		0: "AGENT_TYPE_UNSPECIFIED",
		1: "AGENT_TYPE_ARCHITECT",
		2: "AGENT_TYPE_CODER",
		3: "AGENT_TYPE_TESTER",
		4: "AGENT_TYPE_REVIEWER",
		5: "AGENT_TYPE_RESEARCHER",
		6: "AGENT_TYPE_COORDINATOR",
	}
	AgentType_value = map[string]int32{
		"AGENT_TYPE_UNSPECIFIED": 0,
		"AGENT_TYPE_ARCHITECT":   1,
		"AGENT_TYPE_CODER":       2,
		"AGENT_TYPE_TESTER":      3,
		"AGENT_TYPE_REVIEWER":    4,
		"AGENT_TYPE_RESEARCHER":  5,
		"AGENT_TYPE_COORDINATOR": 6,
	}
)

func (x AgentType) Enum() *AgentType {
	p := new(AgentType)
	*p = x
	return p
}

func (x AgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (AgentType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x AgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentType.Descriptor instead.
func (AgentType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_AGENT_STATUS_CREATED     AgentStatus = 1
	AgentStatus_AGENT_STATUS_READY       AgentStatus = 2
	AgentStatus_AGENT_STATUS_RUNNING     AgentStatus = 3
	AgentStatus_AGENT_STATUS_PAUSED      AgentStatus = 4
	AgentStatus_AGENT_STATUS_ERROR       AgentStatus = 5
	AgentStatus_AGENT_STATUS_TERMINATED  AgentStatus = 6
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_CREATED",
		2: "AGENT_STATUS_READY",
		3: "AGENT_STATUS_RUNNING",
		4: "AGENT_STATUS_PAUSED",
		5: "AGENT_STATUS_ERROR",
		6: "AGENT_STATUS_TERMINATED",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED": 0,
		"AGENT_STATUS_CREATED":     1,
		"AGENT_STATUS_READY":       2,
		"AGENT_STATUS_RUNNING":     3,
		"AGENT_STATUS_PAUSED":      4,
		"AGENT_STATUS_ERROR":       5,
		"AGENT_STATUS_TERMINATED":  6,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1
	TaskStatus_TASK_STATUS_QUEUED      TaskStatus = 2
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 3
	TaskStatus_TASK_STATUS_BLOCKED     TaskStatus = 4
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 5
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 6
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 7
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_QUEUED",
		3: "TASK_STATUS_RUNNING",
		4: "TASK_STATUS_BLOCKED",
		5: "TASK_STATUS_COMPLETED",
		6: "TASK_STATUS_FAILED",
		7: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_QUEUED":      2,
		"TASK_STATUS_RUNNING":     3,
		"TASK_STATUS_BLOCKED":     4,
		"TASK_STATUS_COMPLETED":   5,
		"TASK_STATUS_FAILED":      6,
		"TASK_STATUS_CANCELLED":   7,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type TaskKind int32

const (
	TaskKind_TASK_KIND_UNSPECIFIED TaskKind = 0
	TaskKind_TASK_KIND_COMPUTE     TaskKind = 1
	TaskKind_TASK_KIND_IO          TaskKind = 2
	TaskKind_TASK_KIND_NETWORK     TaskKind = 3
	TaskKind_TASK_KIND_AGGREGATE   TaskKind = 4
	TaskKind_TASK_KIND_DECISION    TaskKind = 5
)

// Enum value maps for TaskKind.
var (
	TaskKind_name = map[int32]string{
		0: "TASK_KIND_UNSPECIFIED",
		1: "TASK_KIND_COMPUTE",
		2: "TASK_KIND_IO",
		3: "TASK_KIND_NETWORK",
		4: "TASK_KIND_AGGREGATE",
		5: "TASK_KIND_DECISION",
	}
	TaskKind_value = map[string]int32{
		"TASK_KIND_UNSPECIFIED": 0,
		"TASK_KIND_COMPUTE":     1,
		"TASK_KIND_IO":          2,
		"TASK_KIND_NETWORK":     3,
		"TASK_KIND_AGGREGATE":   4,
		"TASK_KIND_DECISION":    5,
	}
)

func (x TaskKind) Enum() *TaskKind {
	p := new(TaskKind)
	*p = x
	return p
}

func (x TaskKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskKind) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (TaskKind) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x TaskKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskKind.Descriptor instead.
func (TaskKind) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_NORMAL      Priority = 2
	Priority_PRIORITY_HIGH        Priority = 3
	Priority_PRIORITY_CRITICAL    Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_NORMAL":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_CRITICAL":    4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[4].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[4]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []string               `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\bswarm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"O\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x03(\tR\adetails*\xbe\x01\n" +
	"\tAgentType\x12\x1a\n" +
	"\x16AGENT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14AGENT_TYPE_ARCHITECT\x10\x01\x12\x14\n" +
	"\x10AGENT_TYPE_CODER\x10\x02\x12\x15\n" +
	"\x11AGENT_TYPE_TESTER\x10\x03\x12\x17\n" +
	"\x13AGENT_TYPE_REVIEWER\x10\x04\x12\x19\n" +
	"\x15AGENT_TYPE_RESEARCHER\x10\x05\x12\x1a\n" +
	"\x16AGENT_TYPE_COORDINATOR\x10\x06*\xc5\x01\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14AGENT_STATUS_CREATED\x10\x01\x12\x16\n" +
	"\x12AGENT_STATUS_READY\x10\x02\x12\x18\n" +
	"\x14AGENT_STATUS_RUNNING\x10\x03\x12\x17\n" +
	"\x13AGENT_STATUS_PAUSED\x10\x04\x12\x16\n" +
	"\x12AGENT_STATUS_ERROR\x10\x05\x12\x1b\n" +
	"\x17AGENT_STATUS_TERMINATED\x10\x06*\xda\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12TASK_STATUS_QUEUED\x10\x02\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x03\x12\x17\n" +
	"\x13TASK_STATUS_BLOCKED\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x05\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x06\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\a*\x96\x01\n" +
	"\bTaskKind\x12\x19\n" +
	"\x15TASK_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_KIND_COMPUTE\x10\x01\x12\x10\n" +
	"\fTASK_KIND_IO\x10\x02\x12\x15\n" +
	"\x11TASK_KIND_NETWORK\x10\x03\x12\x17\n" +
	"\x13TASK_KIND_AGGREGATE\x10\x04\x12\x16\n" +
	"\x12TASK_KIND_DECISION\x10\x05*u\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x04B6Z4github.com/swarm-ai/swarm/internal/server/grpc/protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(AgentType)(0),   // 0: swarm.v1.AgentType
	(AgentStatus)(0), // 1: swarm.v1.AgentStatus
	(TaskStatus)(0),  // 2: swarm.v1.TaskStatus
	(TaskKind)(0),    // 3: swarm.v1.TaskKind
	(Priority)(0),    // 4: swarm.v1.Priority
	(*Empty)(nil),    // 5: swarm.v1.Empty
	(*Error)(nil),    // 6: swarm.v1.Error
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
