// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: skill.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SkillService_RegisterSkill_FullMethodName      = "/swarm.v1.SkillService/RegisterSkill"
	SkillService_GetSkill_FullMethodName           = "/swarm.v1.SkillService/GetSkill"
	SkillService_ListSkills_FullMethodName         = "/swarm.v1.SkillService/ListSkills"
	SkillService_UpdateSkill_FullMethodName        = "/swarm.v1.SkillService/UpdateSkill"
	SkillService_DeleteSkill_FullMethodName        = "/swarm.v1.SkillService/DeleteSkill"
	SkillService_DiscoverSkills_FullMethodName     = "/swarm.v1.SkillService/DiscoverSkills"
	SkillService_GetSkillManifest_FullMethodName   = "/swarm.v1.SkillService/GetSkillManifest"
	SkillService_StreamSkillUpdates_FullMethodName = "/swarm.v1.SkillService/StreamSkillUpdates"
)

// SkillServiceClient is the client API for SkillService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkillServiceClient interface {
	RegisterSkill(ctx context.Context, in *RegisterSkillRequest, opts ...grpc.CallOption) (*RegisterSkillResponse, error)
	GetSkill(ctx context.Context, in *GetSkillRequest, opts ...grpc.CallOption) (*GetSkillResponse, error)
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error)
	UpdateSkill(ctx context.Context, in *UpdateSkillRequest, opts ...grpc.CallOption) (*UpdateSkillResponse, error)
	DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DiscoverSkills(ctx context.Context, in *DiscoverSkillsRequest, opts ...grpc.CallOption) (*DiscoverSkillsResponse, error)
	GetSkillManifest(ctx context.Context, in *GetSkillManifestRequest, opts ...grpc.CallOption) (*GetSkillManifestResponse, error)
	StreamSkillUpdates(ctx context.Context, in *StreamSkillUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SkillUpdate], error)
}

type skillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkillServiceClient(cc grpc.ClientConnInterface) SkillServiceClient {
	return &skillServiceClient{cc}
}

func (c *skillServiceClient) RegisterSkill(ctx context.Context, in *RegisterSkillRequest, opts ...grpc.CallOption) (*RegisterSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterSkillResponse)
	err := c.cc.Invoke(ctx, SkillService_RegisterSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) GetSkill(ctx context.Context, in *GetSkillRequest, opts ...grpc.CallOption) (*GetSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSkillResponse)
	err := c.cc.Invoke(ctx, SkillService_GetSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillsResponse)
	err := c.cc.Invoke(ctx, SkillService_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) UpdateSkill(ctx context.Context, in *UpdateSkillRequest, opts ...grpc.CallOption) (*UpdateSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSkillResponse)
	err := c.cc.Invoke(ctx, SkillService_UpdateSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SkillService_DeleteSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) DiscoverSkills(ctx context.Context, in *DiscoverSkillsRequest, opts ...grpc.CallOption) (*DiscoverSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverSkillsResponse)
	err := c.cc.Invoke(ctx, SkillService_DiscoverSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) GetSkillManifest(ctx context.Context, in *GetSkillManifestRequest, opts ...grpc.CallOption) (*GetSkillManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSkillManifestResponse)
	err := c.cc.Invoke(ctx, SkillService_GetSkillManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) StreamSkillUpdates(ctx context.Context, in *StreamSkillUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SkillUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SkillService_ServiceDesc.Streams[0], SkillService_StreamSkillUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSkillUpdatesRequest, SkillUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SkillService_StreamSkillUpdatesClient = grpc.ServerStreamingClient[SkillUpdate]

// SkillServiceServer is the server API for SkillService service.
// All implementations must embed UnimplementedSkillServiceServer
// for forward compatibility.
type SkillServiceServer interface {
	RegisterSkill(context.Context, *RegisterSkillRequest) (*RegisterSkillResponse, error)
	GetSkill(context.Context, *GetSkillRequest) (*GetSkillResponse, error)
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error)
	UpdateSkill(context.Context, *UpdateSkillRequest) (*UpdateSkillResponse, error)
	DeleteSkill(context.Context, *DeleteSkillRequest) (*emptypb.Empty, error)
	DiscoverSkills(context.Context, *DiscoverSkillsRequest) (*DiscoverSkillsResponse, error)
	GetSkillManifest(context.Context, *GetSkillManifestRequest) (*GetSkillManifestResponse, error)
	StreamSkillUpdates(*StreamSkillUpdatesRequest, grpc.ServerStreamingServer[SkillUpdate]) error
	mustEmbedUnimplementedSkillServiceServer()
}

// UnimplementedSkillServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkillServiceServer struct{}

func (UnimplementedSkillServiceServer) RegisterSkill(context.Context, *RegisterSkillRequest) (*RegisterSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSkill not implemented")
}
func (UnimplementedSkillServiceServer) GetSkill(context.Context, *GetSkillRequest) (*GetSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkill not implemented")
}
func (UnimplementedSkillServiceServer) ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedSkillServiceServer) UpdateSkill(context.Context, *UpdateSkillRequest) (*UpdateSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSkill not implemented")
}
func (UnimplementedSkillServiceServer) DeleteSkill(context.Context, *DeleteSkillRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSkill not implemented")
}
func (UnimplementedSkillServiceServer) DiscoverSkills(context.Context, *DiscoverSkillsRequest) (*DiscoverSkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverSkills not implemented")
}
func (UnimplementedSkillServiceServer) GetSkillManifest(context.Context, *GetSkillManifestRequest) (*GetSkillManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkillManifest not implemented")
}
func (UnimplementedSkillServiceServer) StreamSkillUpdates(*StreamSkillUpdatesRequest, grpc.ServerStreamingServer[SkillUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamSkillUpdates not implemented")
}
func (UnimplementedSkillServiceServer) mustEmbedUnimplementedSkillServiceServer() {}
func (UnimplementedSkillServiceServer) testEmbeddedByValue()                      {}

// UnsafeSkillServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkillServiceServer will
// result in compilation errors.
type UnsafeSkillServiceServer interface {
	mustEmbedUnimplementedSkillServiceServer()
}

func RegisterSkillServiceServer(s grpc.ServiceRegistrar, srv SkillServiceServer) {
	// If the following call panics, it indicates UnimplementedSkillServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkillService_ServiceDesc, srv)
}

func _SkillService_RegisterSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).RegisterSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_RegisterSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).RegisterSkill(ctx, req.(*RegisterSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_GetSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).GetSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_GetSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).GetSkill(ctx, req.(*GetSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).ListSkills(ctx, req.(*ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_UpdateSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).UpdateSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_UpdateSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).UpdateSkill(ctx, req.(*UpdateSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_DeleteSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).DeleteSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_DeleteSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).DeleteSkill(ctx, req.(*DeleteSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_DiscoverSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).DiscoverSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_DiscoverSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).DiscoverSkills(ctx, req.(*DiscoverSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_GetSkillManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).GetSkillManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_GetSkillManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).GetSkillManifest(ctx, req.(*GetSkillManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_StreamSkillUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSkillUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SkillServiceServer).StreamSkillUpdates(m, &grpc.GenericServerStream[StreamSkillUpdatesRequest, SkillUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SkillService_StreamSkillUpdatesServer = grpc.ServerStreamingServer[SkillUpdate]

// SkillService_ServiceDesc is the grpc.ServiceDesc for SkillService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swarm.v1.SkillService",
	HandlerType: (*SkillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSkill",
			Handler:    _SkillService_RegisterSkill_Handler,
		},
		{
			MethodName: "GetSkill",
			Handler:    _SkillService_GetSkill_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _SkillService_ListSkills_Handler,
		},
		{
			MethodName: "UpdateSkill",
			Handler:    _SkillService_UpdateSkill_Handler,
		},
		{
			MethodName: "DeleteSkill",
			Handler:    _SkillService_DeleteSkill_Handler,
		},
		{
			MethodName: "DiscoverSkills",
			Handler:    _SkillService_DiscoverSkills_Handler,
		},
		{
			MethodName: "GetSkillManifest",
			Handler:    _SkillService_GetSkillManifest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSkillUpdates",
			Handler:       _SkillService_StreamSkillUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "skill.proto",
}
