// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: skill.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *SkillManifest         `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSkillRequest) Reset() {
	*x = RegisterSkillRequest{}
	mi := &file_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSkillRequest) ProtoMessage() {}

func (x *RegisterSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSkillRequest.ProtoReflect.Descriptor instead.
func (*RegisterSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterSkillRequest) GetManifest() *SkillManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *RegisterSkillRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type RegisterSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *Skill                 `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSkillResponse) Reset() {
	*x = RegisterSkillResponse{}
	mi := &file_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSkillResponse) ProtoMessage() {}

func (x *RegisterSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSkillResponse.ProtoReflect.Descriptor instead.
func (*RegisterSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterSkillResponse) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

type GetSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillRequest) Reset() {
	*x = GetSkillRequest{}
	mi := &file_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillRequest) ProtoMessage() {}

func (x *GetSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillRequest.ProtoReflect.Descriptor instead.
func (*GetSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{2}
}

func (x *GetSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSkillRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *Skill                 `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillResponse) Reset() {
	*x = GetSkillResponse{}
	mi := &file_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillResponse) ProtoMessage() {}

func (x *GetSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillResponse.ProtoReflect.Descriptor instead.
func (*GetSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{3}
}

func (x *GetSkillResponse) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

type ListSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Deprecated    bool                   `protobuf:"varint,3,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsRequest) Reset() {
	*x = ListSkillsRequest{}
	mi := &file_skill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsRequest) ProtoMessage() {}

func (x *ListSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsRequest.ProtoReflect.Descriptor instead.
func (*ListSkillsRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{4}
}

func (x *ListSkillsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListSkillsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListSkillsRequest) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *ListSkillsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSkillsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*Skill               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsResponse) Reset() {
	*x = ListSkillsResponse{}
	mi := &file_skill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsResponse) ProtoMessage() {}

func (x *ListSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsResponse.ProtoReflect.Descriptor instead.
func (*ListSkillsResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{5}
}

func (x *ListSkillsResponse) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ListSkillsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListSkillsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Manifest      *SkillManifest         `protobuf:"bytes,3,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkillRequest) Reset() {
	*x = UpdateSkillRequest{}
	mi := &file_skill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkillRequest) ProtoMessage() {}

func (x *UpdateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkillRequest.ProtoReflect.Descriptor instead.
func (*UpdateSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSkillRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateSkillRequest) GetManifest() *SkillManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type UpdateSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *Skill                 `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkillResponse) Reset() {
	*x = UpdateSkillResponse{}
	mi := &file_skill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkillResponse) ProtoMessage() {}

func (x *UpdateSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkillResponse.ProtoReflect.Descriptor instead.
func (*UpdateSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSkillResponse) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

type DeleteSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkillRequest) Reset() {
	*x = DeleteSkillRequest{}
	mi := &file_skill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillRequest) ProtoMessage() {}

func (x *DeleteSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillRequest.ProtoReflect.Descriptor instead.
func (*DeleteSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteSkillRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DiscoverSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	MinConfidence float64                `protobuf:"fixed64,4,opt,name=min_confidence,json=minConfidence,proto3" json:"min_confidence,omitempty"`
	Context       map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverSkillsRequest) Reset() {
	*x = DiscoverSkillsRequest{}
	mi := &file_skill_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverSkillsRequest) ProtoMessage() {}

func (x *DiscoverSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverSkillsRequest.ProtoReflect.Descriptor instead.
func (*DiscoverSkillsRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{9}
}

func (x *DiscoverSkillsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *DiscoverSkillsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DiscoverSkillsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DiscoverSkillsRequest) GetMinConfidence() float64 {
	if x != nil {
		return x.MinConfidence
	}
	return 0
}

func (x *DiscoverSkillsRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type DiscoverSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*SkillMatch          `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverSkillsResponse) Reset() {
	*x = DiscoverSkillsResponse{}
	mi := &file_skill_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverSkillsResponse) ProtoMessage() {}

func (x *DiscoverSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverSkillsResponse.ProtoReflect.Descriptor instead.
func (*DiscoverSkillsResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{10}
}

func (x *DiscoverSkillsResponse) GetMatches() []*SkillMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type GetSkillManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillManifestRequest) Reset() {
	*x = GetSkillManifestRequest{}
	mi := &file_skill_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillManifestRequest) ProtoMessage() {}

func (x *GetSkillManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillManifestRequest.ProtoReflect.Descriptor instead.
func (*GetSkillManifestRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{11}
}

func (x *GetSkillManifestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSkillManifestRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetSkillManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *SkillManifest         `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillManifestResponse) Reset() {
	*x = GetSkillManifestResponse{}
	mi := &file_skill_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillManifestResponse) ProtoMessage() {}

func (x *GetSkillManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillManifestResponse.ProtoReflect.Descriptor instead.
func (*GetSkillManifestResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{12}
}

func (x *GetSkillManifestResponse) GetManifest() *SkillManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type StreamSkillUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillNames    []string               `protobuf:"bytes,1,rep,name=skill_names,json=skillNames,proto3" json:"skill_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSkillUpdatesRequest) Reset() {
	*x = StreamSkillUpdatesRequest{}
	mi := &file_skill_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSkillUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSkillUpdatesRequest) ProtoMessage() {}

func (x *StreamSkillUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSkillUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamSkillUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{13}
}

func (x *StreamSkillUpdatesRequest) GetSkillNames() []string {
	if x != nil {
		return x.SkillNames
	}
	return nil
}

type SkillUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Skill         *Skill                 `protobuf:"bytes,2,opt,name=skill,proto3" json:"skill,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillUpdate) Reset() {
	*x = SkillUpdate{}
	mi := &file_skill_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillUpdate) ProtoMessage() {}

func (x *SkillUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillUpdate.ProtoReflect.Descriptor instead.
func (*SkillUpdate) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{14}
}

func (x *SkillUpdate) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *SkillUpdate) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

func (x *SkillUpdate) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SkillUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	License       string                 `protobuf:"bytes,7,opt,name=license,proto3" json:"license,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Icon          string                 `protobuf:"bytes,9,opt,name=icon,proto3" json:"icon,omitempty"`
	Homepage      string                 `protobuf:"bytes,10,opt,name=homepage,proto3" json:"homepage,omitempty"`
	Repository    string                 `protobuf:"bytes,11,opt,name=repository,proto3" json:"repository,omitempty"`
	Deprecated    bool                   `protobuf:"varint,12,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_skill_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{15}
}

func (x *Skill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Skill) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skill) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Skill) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *Skill) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Skill) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Skill) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *Skill) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *Skill) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *Skill) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Skill) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SkillManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *SkillMetadata         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *SkillSpec             `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	FilePath      string                 `protobuf:"bytes,6,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillManifest) Reset() {
	*x = SkillManifest{}
	mi := &file_skill_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillManifest) ProtoMessage() {}

func (x *SkillManifest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillManifest.ProtoReflect.Descriptor instead.
func (*SkillManifest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{16}
}

func (x *SkillManifest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *SkillManifest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SkillManifest) GetMetadata() *SkillMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SkillManifest) GetSpec() *SkillSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *SkillManifest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SkillManifest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type SkillMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	License       string                 `protobuf:"bytes,6,opt,name=license,proto3" json:"license,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Icon          string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	Homepage      string                 `protobuf:"bytes,9,opt,name=homepage,proto3" json:"homepage,omitempty"`
	Repository    string                 `protobuf:"bytes,10,opt,name=repository,proto3" json:"repository,omitempty"`
	Deprecated    bool                   `protobuf:"varint,11,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillMetadata) Reset() {
	*x = SkillMetadata{}
	mi := &file_skill_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillMetadata) ProtoMessage() {}

func (x *SkillMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillMetadata.ProtoReflect.Descriptor instead.
func (*SkillMetadata) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{17}
}

func (x *SkillMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SkillMetadata) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SkillMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SkillMetadata) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SkillMetadata) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *SkillMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SkillMetadata) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *SkillMetadata) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *SkillMetadata) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *SkillMetadata) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

type SkillSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       string                 `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Entrypoint    string                 `protobuf:"bytes,2,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Triggers      []*Trigger             `protobuf:"bytes,3,rep,name=triggers,proto3" json:"triggers,omitempty"`
	Tools         []*ToolDef             `protobuf:"bytes,4,rep,name=tools,proto3" json:"tools,omitempty"`
	Prompts       *Prompts               `protobuf:"bytes,5,opt,name=prompts,proto3" json:"prompts,omitempty"`
	Dependencies  []*Dependency          `protobuf:"bytes,6,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Resources     *Resources             `protobuf:"bytes,7,opt,name=resources,proto3" json:"resources,omitempty"`
	Permissions   *Permissions           `protobuf:"bytes,8,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Composition   *Composition           `protobuf:"bytes,9,opt,name=composition,proto3" json:"composition,omitempty"`
	Config        *SkillConfig           `protobuf:"bytes,10,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillSpec) Reset() {
	*x = SkillSpec{}
	mi := &file_skill_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillSpec) ProtoMessage() {}

func (x *SkillSpec) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillSpec.ProtoReflect.Descriptor instead.
func (*SkillSpec) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{18}
}

func (x *SkillSpec) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *SkillSpec) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *SkillSpec) GetTriggers() []*Trigger {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *SkillSpec) GetTools() []*ToolDef {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *SkillSpec) GetPrompts() *Prompts {
	if x != nil {
		return x.Prompts
	}
	return nil
}

func (x *SkillSpec) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *SkillSpec) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *SkillSpec) GetPermissions() *Permissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *SkillSpec) GetComposition() *Composition {
	if x != nil {
		return x.Composition
	}
	return nil
}

func (x *SkillSpec) GetConfig() *SkillConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type Trigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Patterns      []string               `protobuf:"bytes,2,rep,name=patterns,proto3" json:"patterns,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Events        []string               `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	mi := &file_skill_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trigger.ProtoReflect.Descriptor instead.
func (*Trigger) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{19}
}

func (x *Trigger) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Trigger) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *Trigger) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Trigger) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type ToolDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Returns       map[string]string      `protobuf:"bytes,4,rep,name=returns,proto3" json:"returns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDef) Reset() {
	*x = ToolDef{}
	mi := &file_skill_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDef) ProtoMessage() {}

func (x *ToolDef) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDef.ProtoReflect.Descriptor instead.
func (*ToolDef) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{20}
}

func (x *ToolDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDef) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ToolDef) GetReturns() map[string]string {
	if x != nil {
		return x.Returns
	}
	return nil
}

type Prompts struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	System           string                 `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	Examples         []*Example             `protobuf:"bytes,2,rep,name=examples,proto3" json:"examples,omitempty"`
	ContextInjection map[string]string      `protobuf:"bytes,3,rep,name=context_injection,json=contextInjection,proto3" json:"context_injection,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Prompts) Reset() {
	*x = Prompts{}
	mi := &file_skill_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prompts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prompts) ProtoMessage() {}

func (x *Prompts) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prompts.ProtoReflect.Descriptor instead.
func (*Prompts) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{21}
}

func (x *Prompts) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *Prompts) GetExamples() []*Example {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *Prompts) GetContextInjection() map[string]string {
	if x != nil {
		return x.ContextInjection
	}
	return nil
}

type Example struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_skill_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{22}
}

func (x *Example) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Example) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Example) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Dependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Optional      bool                   `protobuf:"varint,4,opt,name=optional,proto3" json:"optional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_skill_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{23}
}

func (x *Dependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Dependency) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Dependency) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	TempStorage   string                 `protobuf:"bytes,4,opt,name=temp_storage,json=tempStorage,proto3" json:"temp_storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_skill_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{24}
}

func (x *Resources) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *Resources) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *Resources) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Resources) GetTempStorage() string {
	if x != nil {
		return x.TempStorage
	}
	return ""
}

type Permissions struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Filesystem    *FilesystemPermissions  `protobuf:"bytes,1,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	Network       *NetworkPermissions     `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Environment   *EnvironmentPermissions `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permissions) Reset() {
	*x = Permissions{}
	mi := &file_skill_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissions) ProtoMessage() {}

func (x *Permissions) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permissions.ProtoReflect.Descriptor instead.
func (*Permissions) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{25}
}

func (x *Permissions) GetFilesystem() *FilesystemPermissions {
	if x != nil {
		return x.Filesystem
	}
	return nil
}

func (x *Permissions) GetNetwork() *NetworkPermissions {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *Permissions) GetEnvironment() *EnvironmentPermissions {
	if x != nil {
		return x.Environment
	}
	return nil
}

type FilesystemPermissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Read          []string               `protobuf:"bytes,1,rep,name=read,proto3" json:"read,omitempty"`
	Write         []string               `protobuf:"bytes,2,rep,name=write,proto3" json:"write,omitempty"`
	Delete        []string               `protobuf:"bytes,3,rep,name=delete,proto3" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemPermissions) Reset() {
	*x = FilesystemPermissions{}
	mi := &file_skill_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemPermissions) ProtoMessage() {}

func (x *FilesystemPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemPermissions.ProtoReflect.Descriptor instead.
func (*FilesystemPermissions) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{26}
}

func (x *FilesystemPermissions) GetRead() []string {
	if x != nil {
		return x.Read
	}
	return nil
}

func (x *FilesystemPermissions) GetWrite() []string {
	if x != nil {
		return x.Write
	}
	return nil
}

func (x *FilesystemPermissions) GetDelete() []string {
	if x != nil {
		return x.Delete
	}
	return nil
}

type NetworkPermissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         bool                   `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`
	AllowedHosts  []string               `protobuf:"bytes,2,rep,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPermissions) Reset() {
	*x = NetworkPermissions{}
	mi := &file_skill_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPermissions) ProtoMessage() {}

func (x *NetworkPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPermissions.ProtoReflect.Descriptor instead.
func (*NetworkPermissions) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{27}
}

func (x *NetworkPermissions) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *NetworkPermissions) GetAllowedHosts() []string {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

type EnvironmentPermissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         []string               `protobuf:"bytes,1,rep,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentPermissions) Reset() {
	*x = EnvironmentPermissions{}
	mi := &file_skill_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentPermissions) ProtoMessage() {}

func (x *EnvironmentPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentPermissions.ProtoReflect.Descriptor instead.
func (*EnvironmentPermissions) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{28}
}

func (x *EnvironmentPermissions) GetAllow() []string {
	if x != nil {
		return x.Allow
	}
	return nil
}

type Composition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CompatibleWith []string               `protobuf:"bytes,1,rep,name=compatible_with,json=compatibleWith,proto3" json:"compatible_with,omitempty"`
	ConflictsWith  []string               `protobuf:"bytes,2,rep,name=conflicts_with,json=conflictsWith,proto3" json:"conflicts_with,omitempty"`
	Enhances       []*Enhancement         `protobuf:"bytes,3,rep,name=enhances,proto3" json:"enhances,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Composition) Reset() {
	*x = Composition{}
	mi := &file_skill_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Composition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Composition) ProtoMessage() {}

func (x *Composition) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Composition.ProtoReflect.Descriptor instead.
func (*Composition) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{29}
}

func (x *Composition) GetCompatibleWith() []string {
	if x != nil {
		return x.CompatibleWith
	}
	return nil
}

func (x *Composition) GetConflictsWith() []string {
	if x != nil {
		return x.ConflictsWith
	}
	return nil
}

func (x *Composition) GetEnhances() []*Enhancement {
	if x != nil {
		return x.Enhances
	}
	return nil
}

type Enhancement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         string                 `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	MinVersion    string                 `protobuf:"bytes,2,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enhancement) Reset() {
	*x = Enhancement{}
	mi := &file_skill_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enhancement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enhancement) ProtoMessage() {}

func (x *Enhancement) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enhancement.ProtoReflect.Descriptor instead.
func (*Enhancement) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{30}
}

func (x *Enhancement) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *Enhancement) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

type SkillConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        map[string]string      `protobuf:"bytes,1,rep,name=schema,proto3" json:"schema,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ui            map[string]string      `protobuf:"bytes,2,rep,name=ui,proto3" json:"ui,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillConfig) Reset() {
	*x = SkillConfig{}
	mi := &file_skill_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillConfig) ProtoMessage() {}

func (x *SkillConfig) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillConfig.ProtoReflect.Descriptor instead.
func (*SkillConfig) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{31}
}

func (x *SkillConfig) GetSchema() map[string]string {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *SkillConfig) GetUi() map[string]string {
	if x != nil {
		return x.Ui
	}
	return nil
}

type SkillMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Context       map[string]string      `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillMatch) Reset() {
	*x = SkillMatch{}
	mi := &file_skill_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillMatch) ProtoMessage() {}

func (x *SkillMatch) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillMatch.ProtoReflect.Descriptor instead.
func (*SkillMatch) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{32}
}

func (x *SkillMatch) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *SkillMatch) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SkillMatch) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_skill_proto protoreflect.FileDescriptor

const file_skill_proto_rawDesc = "" +
	"\n" +
	"\vskill.proto\x12\bswarm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\fcommon.proto\"c\n" +
	"\x14RegisterSkillRequest\x123\n" +
	"\bmanifest\x18\x01 \x01(\v2\x17.swarm.v1.SkillManifestR\bmanifest\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\">\n" +
	"\x15RegisterSkillResponse\x12%\n" +
	"\x05skill\x18\x01 \x01(\v2\x0f.swarm.v1.SkillR\x05skill\"?\n" +
	"\x0fGetSkillRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"9\n" +
	"\x10GetSkillResponse\x12%\n" +
	"\x05skill\x18\x01 \x01(\v2\x0f.swarm.v1.SkillR\x05skill\"\x97\x01\n" +
	"\x11ListSkillsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x03 \x01(\bR\n" +
	"deprecated\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x86\x01\n" +
	"\x12ListSkillsResponse\x12'\n" +
	"\x06skills\x18\x01 \x03(\v2\x0f.swarm.v1.SkillR\x06skills\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"w\n" +
	"\x12UpdateSkillRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x123\n" +
	"\bmanifest\x18\x03 \x01(\v2\x17.swarm.v1.SkillManifestR\bmanifest\"<\n" +
	"\x13UpdateSkillResponse\x12%\n" +
	"\x05skill\x18\x01 \x01(\v2\x0f.swarm.v1.SkillR\x05skill\"B\n" +
	"\x12DeleteSkillRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x82\x02\n" +
	"\x15DiscoverSkillsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12%\n" +
	"\x0emin_confidence\x18\x04 \x01(\x01R\rminConfidence\x12F\n" +
	"\acontext\x18\x05 \x03(\v2,.swarm.v1.DiscoverSkillsRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x16DiscoverSkillsResponse\x12.\n" +
	"\amatches\x18\x01 \x03(\v2\x14.swarm.v1.SkillMatchR\amatches\"G\n" +
	"\x17GetSkillManifestRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"O\n" +
	"\x18GetSkillManifestResponse\x123\n" +
	"\bmanifest\x18\x01 \x01(\v2\x17.swarm.v1.SkillManifestR\bmanifest\"<\n" +
	"\x19StreamSkillUpdatesRequest\x12\x1f\n" +
	"\vskill_names\x18\x01 \x03(\tR\n" +
	"skillNames\"\xa1\x01\n" +
	"\vSkillUpdate\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12%\n" +
	"\x05skill\x18\x02 \x01(\v2\x0f.swarm.v1.SkillR\x05skill\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xb6\x03\n" +
	"\x05Skill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x06 \x01(\tR\x06author\x12\x18\n" +
	"\alicense\x18\a \x01(\tR\alicense\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x12\n" +
	"\x04icon\x18\t \x01(\tR\x04icon\x12\x1a\n" +
	"\bhomepage\x18\n" +
	" \x01(\tR\bhomepage\x12\x1e\n" +
	"\n" +
	"repository\x18\v \x01(\tR\n" +
	"repository\x12\x1e\n" +
	"\n" +
	"deprecated\x18\f \x01(\bR\n" +
	"deprecated\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd7\x01\n" +
	"\rSkillManifest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.swarm.v1.SkillMetadataR\bmetadata\x12'\n" +
	"\x04spec\x18\x04 \x01(\v2\x13.swarm.v1.SkillSpecR\x04spec\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1b\n" +
	"\tfile_path\x18\x06 \x01(\tR\bfilePath\"\xb8\x02\n" +
	"\rSkillMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x18\n" +
	"\alicense\x18\x06 \x01(\tR\alicense\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\x12\x1a\n" +
	"\bhomepage\x18\t \x01(\tR\bhomepage\x12\x1e\n" +
	"\n" +
	"repository\x18\n" +
	" \x01(\tR\n" +
	"repository\x12\x1e\n" +
	"\n" +
	"deprecated\x18\v \x01(\bR\n" +
	"deprecated\"\xd8\x03\n" +
	"\tSkillSpec\x12\x18\n" +
	"\aruntime\x18\x01 \x01(\tR\aruntime\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x02 \x01(\tR\n" +
	"entrypoint\x12-\n" +
	"\btriggers\x18\x03 \x03(\v2\x11.swarm.v1.TriggerR\btriggers\x12'\n" +
	"\x05tools\x18\x04 \x03(\v2\x11.swarm.v1.ToolDefR\x05tools\x12+\n" +
	"\aprompts\x18\x05 \x01(\v2\x11.swarm.v1.PromptsR\aprompts\x128\n" +
	"\fdependencies\x18\x06 \x03(\v2\x14.swarm.v1.DependencyR\fdependencies\x121\n" +
	"\tresources\x18\a \x01(\v2\x13.swarm.v1.ResourcesR\tresources\x127\n" +
	"\vpermissions\x18\b \x01(\v2\x15.swarm.v1.PermissionsR\vpermissions\x127\n" +
	"\vcomposition\x18\t \x01(\v2\x15.swarm.v1.CompositionR\vcomposition\x12-\n" +
	"\x06config\x18\n" +
	" \x01(\v2\x15.swarm.v1.SkillConfigR\x06config\"q\n" +
	"\aTrigger\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bpatterns\x18\x02 \x03(\tR\bpatterns\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x16\n" +
	"\x06events\x18\x04 \x03(\tR\x06events\"\xb7\x02\n" +
	"\aToolDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12A\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2!.swarm.v1.ToolDef.ParametersEntryR\n" +
	"parameters\x128\n" +
	"\areturns\x18\x04 \x03(\v2\x1e.swarm.v1.ToolDef.ReturnsEntryR\areturns\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fReturnsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x01\n" +
	"\aPrompts\x12\x16\n" +
	"\x06system\x18\x01 \x01(\tR\x06system\x12-\n" +
	"\bexamples\x18\x02 \x03(\v2\x11.swarm.v1.ExampleR\bexamples\x12T\n" +
	"\x11context_injection\x18\x03 \x03(\v2'.swarm.v1.Prompts.ContextInjectionEntryR\x10contextInjection\x1aC\n" +
	"\x15ContextInjectionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x01\n" +
	"\aExample\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12;\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1f.swarm.v1.Example.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\n" +
	"Dependency\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1a\n" +
	"\boptional\x18\x04 \x01(\bR\boptional\"w\n" +
	"\tResources\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\tR\x06memory\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\x12!\n" +
	"\ftemp_storage\x18\x04 \x01(\tR\vtempStorage\"\xca\x01\n" +
	"\vPermissions\x12?\n" +
	"\n" +
	"filesystem\x18\x01 \x01(\v2\x1f.swarm.v1.FilesystemPermissionsR\n" +
	"filesystem\x126\n" +
	"\anetwork\x18\x02 \x01(\v2\x1c.swarm.v1.NetworkPermissionsR\anetwork\x12B\n" +
	"\venvironment\x18\x03 \x01(\v2 .swarm.v1.EnvironmentPermissionsR\venvironment\"Y\n" +
	"\x15FilesystemPermissions\x12\x12\n" +
	"\x04read\x18\x01 \x03(\tR\x04read\x12\x14\n" +
	"\x05write\x18\x02 \x03(\tR\x05write\x12\x16\n" +
	"\x06delete\x18\x03 \x03(\tR\x06delete\"O\n" +
	"\x12NetworkPermissions\x12\x14\n" +
	"\x05allow\x18\x01 \x01(\bR\x05allow\x12#\n" +
	"\rallowed_hosts\x18\x02 \x03(\tR\fallowedHosts\".\n" +
	"\x16EnvironmentPermissions\x12\x14\n" +
	"\x05allow\x18\x01 \x03(\tR\x05allow\"\x90\x01\n" +
	"\vComposition\x12'\n" +
	"\x0fcompatible_with\x18\x01 \x03(\tR\x0ecompatibleWith\x12%\n" +
	"\x0econflicts_with\x18\x02 \x03(\tR\rconflictsWith\x121\n" +
	"\benhances\x18\x03 \x03(\v2\x15.swarm.v1.EnhancementR\benhances\"D\n" +
	"\vEnhancement\x12\x14\n" +
	"\x05skill\x18\x01 \x01(\tR\x05skill\x12\x1f\n" +
	"\vmin_version\x18\x02 \x01(\tR\n" +
	"minVersion\"\xe9\x01\n" +
	"\vSkillConfig\x129\n" +
	"\x06schema\x18\x01 \x03(\v2!.swarm.v1.SkillConfig.SchemaEntryR\x06schema\x12-\n" +
	"\x02ui\x18\x02 \x03(\v2\x1d.swarm.v1.SkillConfig.UiEntryR\x02ui\x1a9\n" +
	"\vSchemaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a5\n" +
	"\aUiEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\n" +
	"SkillMatch\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12;\n" +
	"\acontext\x18\x03 \x03(\v2!.swarm.v1.SkillMatch.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x81\x05\n" +
	"\fSkillService\x12P\n" +
	"\rRegisterSkill\x12\x1e.swarm.v1.RegisterSkillRequest\x1a\x1f.swarm.v1.RegisterSkillResponse\x12A\n" +
	"\bGetSkill\x12\x19.swarm.v1.GetSkillRequest\x1a\x1a.swarm.v1.GetSkillResponse\x12G\n" +
	"\n" +
	"ListSkills\x12\x1b.swarm.v1.ListSkillsRequest\x1a\x1c.swarm.v1.ListSkillsResponse\x12J\n" +
	"\vUpdateSkill\x12\x1c.swarm.v1.UpdateSkillRequest\x1a\x1d.swarm.v1.UpdateSkillResponse\x12C\n" +
	"\vDeleteSkill\x12\x1c.swarm.v1.DeleteSkillRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\x0eDiscoverSkills\x12\x1f.swarm.v1.DiscoverSkillsRequest\x1a .swarm.v1.DiscoverSkillsResponse\x12Y\n" +
	"\x10GetSkillManifest\x12!.swarm.v1.GetSkillManifestRequest\x1a\".swarm.v1.GetSkillManifestResponse\x12R\n" +
	"\x12StreamSkillUpdates\x12#.swarm.v1.StreamSkillUpdatesRequest\x1a\x15.swarm.v1.SkillUpdate0\x01B6Z4github.com/swarm-ai/swarm/internal/server/grpc/protob\x06proto3"

var (
	file_skill_proto_rawDescOnce sync.Once
	file_skill_proto_rawDescData []byte
)

func file_skill_proto_rawDescGZIP() []byte {
	file_skill_proto_rawDescOnce.Do(func() {
		file_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skill_proto_rawDesc), len(file_skill_proto_rawDesc)))
	})
	return file_skill_proto_rawDescData
}

var file_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_skill_proto_goTypes = []any{
	(*RegisterSkillRequest)(nil),      // 0: swarm.v1.RegisterSkillRequest
	(*RegisterSkillResponse)(nil),     // 1: swarm.v1.RegisterSkillResponse
	(*GetSkillRequest)(nil),           // 2: swarm.v1.GetSkillRequest
	(*GetSkillResponse)(nil),          // 3: swarm.v1.GetSkillResponse
	(*ListSkillsRequest)(nil),         // 4: swarm.v1.ListSkillsRequest
	(*ListSkillsResponse)(nil),        // 5: swarm.v1.ListSkillsResponse
	(*UpdateSkillRequest)(nil),        // 6: swarm.v1.UpdateSkillRequest
	(*UpdateSkillResponse)(nil),       // 7: swarm.v1.UpdateSkillResponse
	(*DeleteSkillRequest)(nil),        // 8: swarm.v1.DeleteSkillRequest
	(*DiscoverSkillsRequest)(nil),     // 9: swarm.v1.DiscoverSkillsRequest
	(*DiscoverSkillsResponse)(nil),    // 10: swarm.v1.DiscoverSkillsResponse
	(*GetSkillManifestRequest)(nil),   // 11: swarm.v1.GetSkillManifestRequest
	(*GetSkillManifestResponse)(nil),  // 12: swarm.v1.GetSkillManifestResponse
	(*StreamSkillUpdatesRequest)(nil), // 13: swarm.v1.StreamSkillUpdatesRequest
	(*SkillUpdate)(nil),               // 14: swarm.v1.SkillUpdate
	(*Skill)(nil),                     // 15: swarm.v1.Skill
	(*SkillManifest)(nil),             // 16: swarm.v1.SkillManifest
	(*SkillMetadata)(nil),             // 17: swarm.v1.SkillMetadata
	(*SkillSpec)(nil),                 // 18: swarm.v1.SkillSpec
	(*Trigger)(nil),                   // 19: swarm.v1.Trigger
	(*ToolDef)(nil),                   // 20: swarm.v1.ToolDef
	(*Prompts)(nil),                   // 21: swarm.v1.Prompts
	(*Example)(nil),                   // 22: swarm.v1.Example
	(*Dependency)(nil),                // 23: swarm.v1.Dependency
	(*Resources)(nil),                 // 24: swarm.v1.Resources
	(*Permissions)(nil),               // 25: swarm.v1.Permissions
	(*FilesystemPermissions)(nil),     // 26: swarm.v1.FilesystemPermissions
	(*NetworkPermissions)(nil),        // 27: swarm.v1.NetworkPermissions
	(*EnvironmentPermissions)(nil),    // 28: swarm.v1.EnvironmentPermissions
	(*Composition)(nil),               // 29: swarm.v1.Composition
	(*Enhancement)(nil),               // 30: swarm.v1.Enhancement
	(*SkillConfig)(nil),               // 31: swarm.v1.SkillConfig
	(*SkillMatch)(nil),                // 32: swarm.v1.SkillMatch
	nil,                               // 33: swarm.v1.DiscoverSkillsRequest.ContextEntry
	nil,                               // 34: swarm.v1.ToolDef.ParametersEntry
	nil,                               // 35: swarm.v1.ToolDef.ReturnsEntry
	nil,                               // 36: swarm.v1.Prompts.ContextInjectionEntry
	nil,                               // 37: swarm.v1.Example.MetadataEntry
	nil,                               // 38: swarm.v1.SkillConfig.SchemaEntry
	nil,                               // 39: swarm.v1.SkillConfig.UiEntry
	nil,                               // 40: swarm.v1.SkillMatch.ContextEntry
	(*timestamppb.Timestamp)(nil),     // 41: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 42: google.protobuf.Empty
}
var file_skill_proto_depIdxs = []int32{
	16, // 0: swarm.v1.RegisterSkillRequest.manifest:type_name -> swarm.v1.SkillManifest
	15, // 1: swarm.v1.RegisterSkillResponse.skill:type_name -> swarm.v1.Skill
	15, // 2: swarm.v1.GetSkillResponse.skill:type_name -> swarm.v1.Skill
	15, // 3: swarm.v1.ListSkillsResponse.skills:type_name -> swarm.v1.Skill
	16, // 4: swarm.v1.UpdateSkillRequest.manifest:type_name -> swarm.v1.SkillManifest
	15, // 5: swarm.v1.UpdateSkillResponse.skill:type_name -> swarm.v1.Skill
	33, // 6: swarm.v1.DiscoverSkillsRequest.context:type_name -> swarm.v1.DiscoverSkillsRequest.ContextEntry
	32, // 7: swarm.v1.DiscoverSkillsResponse.matches:type_name -> swarm.v1.SkillMatch
	16, // 8: swarm.v1.GetSkillManifestResponse.manifest:type_name -> swarm.v1.SkillManifest
	15, // 9: swarm.v1.SkillUpdate.skill:type_name -> swarm.v1.Skill
	41, // 10: swarm.v1.SkillUpdate.timestamp:type_name -> google.protobuf.Timestamp
	41, // 11: swarm.v1.Skill.created_at:type_name -> google.protobuf.Timestamp
	41, // 12: swarm.v1.Skill.updated_at:type_name -> google.protobuf.Timestamp
	17, // 13: swarm.v1.SkillManifest.metadata:type_name -> swarm.v1.SkillMetadata
	18, // 14: swarm.v1.SkillManifest.spec:type_name -> swarm.v1.SkillSpec
	19, // 15: swarm.v1.SkillSpec.triggers:type_name -> swarm.v1.Trigger
	20, // 16: swarm.v1.SkillSpec.tools:type_name -> swarm.v1.ToolDef
	21, // 17: swarm.v1.SkillSpec.prompts:type_name -> swarm.v1.Prompts
	23, // 18: swarm.v1.SkillSpec.dependencies:type_name -> swarm.v1.Dependency
	24, // 19: swarm.v1.SkillSpec.resources:type_name -> swarm.v1.Resources
	25, // 20: swarm.v1.SkillSpec.permissions:type_name -> swarm.v1.Permissions
	29, // 21: swarm.v1.SkillSpec.composition:type_name -> swarm.v1.Composition
	31, // 22: swarm.v1.SkillSpec.config:type_name -> swarm.v1.SkillConfig
	34, // 23: swarm.v1.ToolDef.parameters:type_name -> swarm.v1.ToolDef.ParametersEntry
	35, // 24: swarm.v1.ToolDef.returns:type_name -> swarm.v1.ToolDef.ReturnsEntry
	22, // 25: swarm.v1.Prompts.examples:type_name -> swarm.v1.Example
	36, // 26: swarm.v1.Prompts.context_injection:type_name -> swarm.v1.Prompts.ContextInjectionEntry
	37, // 27: swarm.v1.Example.metadata:type_name -> swarm.v1.Example.MetadataEntry
	26, // 28: swarm.v1.Permissions.filesystem:type_name -> swarm.v1.FilesystemPermissions
	27, // 29: swarm.v1.Permissions.network:type_name -> swarm.v1.NetworkPermissions
	28, // 30: swarm.v1.Permissions.environment:type_name -> swarm.v1.EnvironmentPermissions
	30, // 31: swarm.v1.Composition.enhances:type_name -> swarm.v1.Enhancement
	38, // 32: swarm.v1.SkillConfig.schema:type_name -> swarm.v1.SkillConfig.SchemaEntry
	39, // 33: swarm.v1.SkillConfig.ui:type_name -> swarm.v1.SkillConfig.UiEntry
	40, // 34: swarm.v1.SkillMatch.context:type_name -> swarm.v1.SkillMatch.ContextEntry
	0,  // 35: swarm.v1.SkillService.RegisterSkill:input_type -> swarm.v1.RegisterSkillRequest
	2,  // 36: swarm.v1.SkillService.GetSkill:input_type -> swarm.v1.GetSkillRequest
	4,  // 37: swarm.v1.SkillService.ListSkills:input_type -> swarm.v1.ListSkillsRequest
	6,  // 38: swarm.v1.SkillService.UpdateSkill:input_type -> swarm.v1.UpdateSkillRequest
	8,  // 39: swarm.v1.SkillService.DeleteSkill:input_type -> swarm.v1.DeleteSkillRequest
	9,  // 40: swarm.v1.SkillService.DiscoverSkills:input_type -> swarm.v1.DiscoverSkillsRequest
	11, // 41: swarm.v1.SkillService.GetSkillManifest:input_type -> swarm.v1.GetSkillManifestRequest
	13, // 42: swarm.v1.SkillService.StreamSkillUpdates:input_type -> swarm.v1.StreamSkillUpdatesRequest
	1,  // 43: swarm.v1.SkillService.RegisterSkill:output_type -> swarm.v1.RegisterSkillResponse
	3,  // 44: swarm.v1.SkillService.GetSkill:output_type -> swarm.v1.GetSkillResponse
	5,  // 45: swarm.v1.SkillService.ListSkills:output_type -> swarm.v1.ListSkillsResponse
	7,  // 46: swarm.v1.SkillService.UpdateSkill:output_type -> swarm.v1.UpdateSkillResponse
	42, // 47: swarm.v1.SkillService.DeleteSkill:output_type -> google.protobuf.Empty
	10, // 48: swarm.v1.SkillService.DiscoverSkills:output_type -> swarm.v1.DiscoverSkillsResponse
	12, // 49: swarm.v1.SkillService.GetSkillManifest:output_type -> swarm.v1.GetSkillManifestResponse
	14, // 50: swarm.v1.SkillService.StreamSkillUpdates:output_type -> swarm.v1.SkillUpdate
	43, // [43:51] is the sub-list for method output_type
	35, // [35:43] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_skill_proto_init() }
func file_skill_proto_init() {
	if File_skill_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skill_proto_rawDesc), len(file_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skill_proto_goTypes,
		DependencyIndexes: file_skill_proto_depIdxs,
		MessageInfos:      file_skill_proto_msgTypes,
	}.Build()
	File_skill_proto = out.File
	file_skill_proto_goTypes = nil
	file_skill_proto_depIdxs = nil
}
