// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: task.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	AgentType     AgentType              `protobuf:"varint,5,opt,name=agent_type,json=agentType,proto3,enum=swarm.v1.AgentType" json:"agent_type,omitempty"`
	AssignedAgent string                 `protobuf:"bytes,6,opt,name=assigned_agent,json=assignedAgent,proto3" json:"assigned_agent,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Dependencies  []string               `protobuf:"bytes,8,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Input         map[string]string      `protobuf:"bytes,9,rep,name=input,proto3" json:"input,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutMs     int64                  `protobuf:"varint,10,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,11,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Kind          TaskKind               `protobuf:"varint,13,opt,name=kind,proto3,enum=swarm.v1.TaskKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CreateTaskRequest) GetAgentType() AgentType {
	if x != nil {
		return x.AgentType
	}
	return AgentType_AGENT_TYPE_UNSPECIFIED
}

func (x *CreateTaskRequest) GetAssignedAgent() string {
	if x != nil {
		return x.AssignedAgent
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateTaskRequest) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *CreateTaskRequest) GetInput() map[string]string {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CreateTaskRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *CreateTaskRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *CreateTaskRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateTaskRequest) GetKind() TaskKind {
	if x != nil {
		return x.Kind
	}
	return TaskKind_TASK_KIND_UNSPECIFIED
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TaskStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=swarm.v1.TaskStatus" json:"status,omitempty"`
	AgentType     AgentType              `protobuf:"varint,2,opt,name=agent_type,json=agentType,proto3,enum=swarm.v1.AgentType" json:"agent_type,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	CreatedAfter  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_after,json=createdAfter,proto3" json:"created_after,omitempty"`
	CreatedBefore *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_before,json=createdBefore,proto3" json:"created_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *ListTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *ListTasksRequest) GetAgentType() AgentType {
	if x != nil {
		return x.AgentType
	}
	return AgentType_AGENT_TYPE_UNSPECIFIED
}

func (x *ListTasksRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListTasksRequest) GetCreatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAfter
	}
	return nil
}

func (x *ListTasksRequest) GetCreatedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedBefore
	}
	return nil
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{5}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListTasksResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Input         map[string]string      `protobuf:"bytes,6,rep,name=input,proto3" json:"input,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *UpdateTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *UpdateTaskRequest) GetInput() map[string]string {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *UpdateTaskRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ExecuteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskRequest) Reset() {
	*x = ExecuteTaskRequest{}
	mi := &file_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskRequest) ProtoMessage() {}

func (x *ExecuteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteTaskRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ExecuteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *TaskResult            `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskResponse) Reset() {
	*x = ExecuteTaskResponse{}
	mi := &file_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskResponse) ProtoMessage() {}

func (x *ExecuteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteTaskResponse) GetResult() *TaskResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{11}
}

func (x *CancelTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_task_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{12}
}

func (x *CancelTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type RetryTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskRequest) Reset() {
	*x = RetryTaskRequest{}
	mi := &file_task_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskRequest) ProtoMessage() {}

func (x *RetryTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskRequest.ProtoReflect.Descriptor instead.
func (*RetryTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{13}
}

func (x *RetryTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RetryTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskResponse) Reset() {
	*x = RetryTaskResponse{}
	mi := &file_task_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskResponse) ProtoMessage() {}

func (x *RetryTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskResponse.ProtoReflect.Descriptor instead.
func (*RetryTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{14}
}

func (x *RetryTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTaskDependenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskDependenciesRequest) Reset() {
	*x = ListTaskDependenciesRequest{}
	mi := &file_task_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskDependenciesRequest) ProtoMessage() {}

func (x *ListTaskDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskDependenciesRequest.ProtoReflect.Descriptor instead.
func (*ListTaskDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{15}
}

func (x *ListTaskDependenciesRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ListTaskDependenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dependencies  []*TaskDependency      `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskDependenciesResponse) Reset() {
	*x = ListTaskDependenciesResponse{}
	mi := &file_task_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskDependenciesResponse) ProtoMessage() {}

func (x *ListTaskDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskDependenciesResponse.ProtoReflect.Descriptor instead.
func (*ListTaskDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{16}
}

func (x *ListTaskDependenciesResponse) GetDependencies() []*TaskDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type StreamTaskUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTaskUpdatesRequest) Reset() {
	*x = StreamTaskUpdatesRequest{}
	mi := &file_task_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTaskUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTaskUpdatesRequest) ProtoMessage() {}

func (x *StreamTaskUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTaskUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamTaskUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{17}
}

func (x *StreamTaskUpdatesRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=swarm.v1.TaskStatus" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskUpdate) Reset() {
	*x = TaskUpdate{}
	mi := &file_task_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUpdate) ProtoMessage() {}

func (x *TaskUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUpdate.ProtoReflect.Descriptor instead.
func (*TaskUpdate) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{18}
}

func (x *TaskUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskUpdate) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TaskUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamTaskProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	IntervalMs    int64                  `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTaskProgressRequest) Reset() {
	*x = StreamTaskProgressRequest{}
	mi := &file_task_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTaskProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTaskProgressRequest) ProtoMessage() {}

func (x *StreamTaskProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTaskProgressRequest.ProtoReflect.Descriptor instead.
func (*StreamTaskProgressRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{19}
}

func (x *StreamTaskProgressRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StreamTaskProgressRequest) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type TaskProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Progress      float64                `protobuf:"fixed64,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StatusMessage string                 `protobuf:"bytes,4,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProgressUpdate) Reset() {
	*x = TaskProgressUpdate{}
	mi := &file_task_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgressUpdate) ProtoMessage() {}

func (x *TaskProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgressUpdate.ProtoReflect.Descriptor instead.
func (*TaskProgressUpdate) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{20}
}

func (x *TaskProgressUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskProgressUpdate) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TaskProgressUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TaskProgressUpdate) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Status        TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=swarm.v1.TaskStatus" json:"status,omitempty"`
	Kind          TaskKind               `protobuf:"varint,6,opt,name=kind,proto3,enum=swarm.v1.TaskKind" json:"kind,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	AgentType     AgentType              `protobuf:"varint,8,opt,name=agent_type,json=agentType,proto3,enum=swarm.v1.AgentType" json:"agent_type,omitempty"`
	AssignedAgent string                 `protobuf:"bytes,9,opt,name=assigned_agent,json=assignedAgent,proto3" json:"assigned_agent,omitempty"`
	Dependencies  []string               `protobuf:"bytes,10,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Input         map[string]string      `protobuf:"bytes,11,rep,name=input,proto3" json:"input,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Output        map[string]string      `protobuf:"bytes,12,rep,name=output,proto3" json:"output,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,17,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	RetryCount    int32                  `protobuf:"varint,18,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,19,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Progress      float64                `protobuf:"fixed64,20,opt,name=progress,proto3" json:"progress,omitempty"`
	Result        *TaskResult            `protobuf:"bytes,21,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,22,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,23,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{21}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetKind() TaskKind {
	if x != nil {
		return x.Kind
	}
	return TaskKind_TASK_KIND_UNSPECIFIED
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetAgentType() AgentType {
	if x != nil {
		return x.AgentType
	}
	return AgentType_AGENT_TYPE_UNSPECIFIED
}

func (x *Task) GetAssignedAgent() string {
	if x != nil {
		return x.AssignedAgent
	}
	return ""
}

func (x *Task) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Task) GetInput() map[string]string {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Task) GetOutput() map[string]string {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Task) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Task) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Task) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Task) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Task) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Task) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Task) GetResult() *TaskResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Task) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Task) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Artifacts     []*Artifact            `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Metrics       *TaskMetrics           `protobuf:"bytes,5,opt,name=metrics,proto3" json:"metrics,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_task_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{22}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskResult) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *TaskResult) GetMetrics() *TaskMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *TaskResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type TaskMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,4,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	ToolCalls     int32                  `protobuf:"varint,5,opt,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Messages      int32                  `protobuf:"varint,6,opt,name=messages,proto3" json:"messages,omitempty"`
	RetryCount    int32                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMetrics) Reset() {
	*x = TaskMetrics{}
	mi := &file_task_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMetrics) ProtoMessage() {}

func (x *TaskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMetrics.ProtoReflect.Descriptor instead.
func (*TaskMetrics) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{23}
}

func (x *TaskMetrics) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TaskMetrics) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *TaskMetrics) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TaskMetrics) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *TaskMetrics) GetToolCalls() int32 {
	if x != nil {
		return x.ToolCalls
	}
	return 0
}

func (x *TaskMetrics) GetMessages() int32 {
	if x != nil {
		return x.Messages
	}
	return 0
}

func (x *TaskMetrics) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_task_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{24}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Artifact) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Artifact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TaskDependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	DependsOn     string                 `protobuf:"bytes,2,opt,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDependency) Reset() {
	*x = TaskDependency{}
	mi := &file_task_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDependency) ProtoMessage() {}

func (x *TaskDependency) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDependency.ProtoReflect.Descriptor instead.
func (*TaskDependency) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{25}
}

func (x *TaskDependency) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskDependency) GetDependsOn() string {
	if x != nil {
		return x.DependsOn
	}
	return ""
}

func (x *TaskDependency) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\bswarm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\fcommon.proto\"\xf0\x04\n" +
	"\x11CreateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x122\n" +
	"\n" +
	"agent_type\x18\x05 \x01(\x0e2\x13.swarm.v1.AgentTypeR\tagentType\x12%\n" +
	"\x0eassigned_agent\x18\x06 \x01(\tR\rassignedAgent\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12\"\n" +
	"\fdependencies\x18\b \x03(\tR\fdependencies\x12<\n" +
	"\x05input\x18\t \x03(\v2&.swarm.v1.CreateTaskRequest.InputEntryR\x05input\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\n" +
	" \x01(\x03R\ttimeoutMs\x12\x1f\n" +
	"\vmax_retries\x18\v \x01(\x05R\n" +
	"maxRetries\x12E\n" +
	"\bmetadata\x18\f \x03(\v2).swarm.v1.CreateTaskRequest.MetadataEntryR\bmetadata\x12&\n" +
	"\x04kind\x18\r \x01(\x0e2\x12.swarm.v1.TaskKindR\x04kind\x1a8\n" +
	"\n" +
	"InputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x12CreateTaskResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.swarm.v1.TaskR\x04task\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x0fGetTaskResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.swarm.v1.TaskR\x04task\"\xcf\x02\n" +
	"\x10ListTasksRequest\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.swarm.v1.TaskStatusR\x06status\x122\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\x0e2\x13.swarm.v1.AgentTypeR\tagentType\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\x12?\n" +
	"\rcreated_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fcreatedAfter\x12A\n" +
	"\x0ecreated_before\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rcreatedBefore\"\x82\x01\n" +
	"\x11ListTasksResponse\x12$\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0e.swarm.v1.TaskR\x05tasks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\x89\x03\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12<\n" +
	"\x05input\x18\x06 \x03(\v2&.swarm.v1.UpdateTaskRequest.InputEntryR\x05input\x12E\n" +
	"\bmetadata\x18\a \x03(\v2).swarm.v1.UpdateTaskRequest.MetadataEntryR\bmetadata\x1a8\n" +
	"\n" +
	"InputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x12UpdateTaskResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.swarm.v1.TaskR\x04task\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x12ExecuteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"C\n" +
	"\x13ExecuteTaskResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.swarm.v1.TaskResultR\x06result\"#\n" +
	"\x11CancelTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x12CancelTaskResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.swarm.v1.TaskR\x04task\"\"\n" +
	"\x10RetryTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x11RetryTaskResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.swarm.v1.TaskR\x04task\"6\n" +
	"\x1bListTaskDependenciesRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\\\n" +
	"\x1cListTaskDependenciesResponse\x12<\n" +
	"\fdependencies\x18\x01 \x03(\v2\x18.swarm.v1.TaskDependencyR\fdependencies\"3\n" +
	"\x18StreamTaskUpdatesRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xa7\x01\n" +
	"\n" +
	"TaskUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.swarm.v1.TaskStatusR\x06status\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"U\n" +
	"\x19StreamTaskProgressRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\x03R\n" +
	"intervalMs\"\xaa\x01\n" +
	"\x12TaskProgressUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x01R\bprogress\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12%\n" +
	"\x0estatus_message\x18\x04 \x01(\tR\rstatusMessage\"\xd7\b\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.swarm.v1.TaskStatusR\x06status\x12&\n" +
	"\x04kind\x18\x06 \x01(\x0e2\x12.swarm.v1.TaskKindR\x04kind\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x122\n" +
	"\n" +
	"agent_type\x18\b \x01(\x0e2\x13.swarm.v1.AgentTypeR\tagentType\x12%\n" +
	"\x0eassigned_agent\x18\t \x01(\tR\rassignedAgent\x12\"\n" +
	"\fdependencies\x18\n" +
	" \x03(\tR\fdependencies\x12/\n" +
	"\x05input\x18\v \x03(\v2\x19.swarm.v1.Task.InputEntryR\x05input\x122\n" +
	"\x06output\x18\f \x03(\v2\x1a.swarm.v1.Task.OutputEntryR\x06output\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"started_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x11 \x01(\x03R\ttimeoutMs\x12\x1f\n" +
	"\vretry_count\x18\x12 \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\x13 \x01(\x05R\n" +
	"maxRetries\x12\x1a\n" +
	"\bprogress\x18\x14 \x01(\x01R\bprogress\x12,\n" +
	"\x06result\x18\x15 \x01(\v2\x14.swarm.v1.TaskResultR\x06result\x12\x14\n" +
	"\x05error\x18\x16 \x01(\tR\x05error\x128\n" +
	"\bmetadata\x18\x17 \x03(\v2\x1c.swarm.v1.Task.MetadataEntryR\bmetadata\x1a8\n" +
	"\n" +
	"InputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vOutputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x120\n" +
	"\tartifacts\x18\x04 \x03(\v2\x12.swarm.v1.ArtifactR\tartifacts\x12/\n" +
	"\ametrics\x18\x05 \x01(\v2\x15.swarm.v1.TaskMetricsR\ametrics\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x9d\x02\n" +
	"\vTaskMetrics\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12\x1f\n" +
	"\vtokens_used\x18\x04 \x01(\x05R\n" +
	"tokensUsed\x12\x1d\n" +
	"\n" +
	"tool_calls\x18\x05 \x01(\x05R\ttoolCalls\x12\x1a\n" +
	"\bmessages\x18\x06 \x01(\x05R\bmessages\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\x05R\n" +
	"retryCount\"\x92\x02\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12<\n" +
	"\bmetadata\x18\x05 \x03(\v2 .swarm.v1.Artifact.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x0eTaskDependency\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x02 \x01(\tR\tdependsOn\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\xd6\x06\n" +
	"\vTaskService\x12G\n" +
	"\n" +
	"CreateTask\x12\x1b.swarm.v1.CreateTaskRequest\x1a\x1c.swarm.v1.CreateTaskResponse\x12>\n" +
	"\aGetTask\x12\x18.swarm.v1.GetTaskRequest\x1a\x19.swarm.v1.GetTaskResponse\x12D\n" +
	"\tListTasks\x12\x1a.swarm.v1.ListTasksRequest\x1a\x1b.swarm.v1.ListTasksResponse\x12G\n" +
	"\n" +
	"UpdateTask\x12\x1b.swarm.v1.UpdateTaskRequest\x1a\x1c.swarm.v1.UpdateTaskResponse\x12A\n" +
	"\n" +
	"DeleteTask\x12\x1b.swarm.v1.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\vExecuteTask\x12\x1c.swarm.v1.ExecuteTaskRequest\x1a\x1d.swarm.v1.ExecuteTaskResponse\x12G\n" +
	"\n" +
	"CancelTask\x12\x1b.swarm.v1.CancelTaskRequest\x1a\x1c.swarm.v1.CancelTaskResponse\x12D\n" +
	"\tRetryTask\x12\x1a.swarm.v1.RetryTaskRequest\x1a\x1b.swarm.v1.RetryTaskResponse\x12e\n" +
	"\x14ListTaskDependencies\x12%.swarm.v1.ListTaskDependenciesRequest\x1a&.swarm.v1.ListTaskDependenciesResponse\x12O\n" +
	"\x11StreamTaskUpdates\x12\".swarm.v1.StreamTaskUpdatesRequest\x1a\x14.swarm.v1.TaskUpdate0\x01\x12Y\n" +
	"\x12StreamTaskProgress\x12#.swarm.v1.StreamTaskProgressRequest\x1a\x1c.swarm.v1.TaskProgressUpdate0\x01B6Z4github.com/swarm-ai/swarm/internal/server/grpc/protob\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_task_proto_goTypes = []any{
	(*CreateTaskRequest)(nil),            // 0: swarm.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),           // 1: swarm.v1.CreateTaskResponse
	(*GetTaskRequest)(nil),               // 2: swarm.v1.GetTaskRequest
	(*GetTaskResponse)(nil),              // 3: swarm.v1.GetTaskResponse
	(*ListTasksRequest)(nil),             // 4: swarm.v1.ListTasksRequest
	(*ListTasksResponse)(nil),            // 5: swarm.v1.ListTasksResponse
	(*UpdateTaskRequest)(nil),            // 6: swarm.v1.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),           // 7: swarm.v1.UpdateTaskResponse
	(*DeleteTaskRequest)(nil),            // 8: swarm.v1.DeleteTaskRequest
	(*ExecuteTaskRequest)(nil),           // 9: swarm.v1.ExecuteTaskRequest
	(*ExecuteTaskResponse)(nil),          // 10: swarm.v1.ExecuteTaskResponse
	(*CancelTaskRequest)(nil),            // 11: swarm.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),           // 12: swarm.v1.CancelTaskResponse
	(*RetryTaskRequest)(nil),             // 13: swarm.v1.RetryTaskRequest
	(*RetryTaskResponse)(nil),            // 14: swarm.v1.RetryTaskResponse
	(*ListTaskDependenciesRequest)(nil),  // 15: swarm.v1.ListTaskDependenciesRequest
	(*ListTaskDependenciesResponse)(nil), // 16: swarm.v1.ListTaskDependenciesResponse
	(*StreamTaskUpdatesRequest)(nil),     // 17: swarm.v1.StreamTaskUpdatesRequest
	(*TaskUpdate)(nil),                   // 18: swarm.v1.TaskUpdate
	(*StreamTaskProgressRequest)(nil),    // 19: swarm.v1.StreamTaskProgressRequest
	(*TaskProgressUpdate)(nil),           // 20: swarm.v1.TaskProgressUpdate
	(*Task)(nil),                         // 21: swarm.v1.Task
	(*TaskResult)(nil),                   // 22: swarm.v1.TaskResult
	(*TaskMetrics)(nil),                  // 23: swarm.v1.TaskMetrics
	(*Artifact)(nil),                     // 24: swarm.v1.Artifact
	(*TaskDependency)(nil),               // 25: swarm.v1.TaskDependency
	nil,                                  // 26: swarm.v1.CreateTaskRequest.InputEntry
	nil,                                  // 27: swarm.v1.CreateTaskRequest.MetadataEntry
	nil,                                  // 28: swarm.v1.UpdateTaskRequest.InputEntry
	nil,                                  // 29: swarm.v1.UpdateTaskRequest.MetadataEntry
	nil,                                  // 30: swarm.v1.Task.InputEntry
	nil,                                  // 31: swarm.v1.Task.OutputEntry
	nil,                                  // 32: swarm.v1.Task.MetadataEntry
	nil,                                  // 33: swarm.v1.Artifact.MetadataEntry
	(AgentType)(0),                       // 34: swarm.v1.AgentType
	(TaskKind)(0),                        // 35: swarm.v1.TaskKind
	(TaskStatus)(0),                      // 36: swarm.v1.TaskStatus
	(*timestamppb.Timestamp)(nil),        // 37: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 38: google.protobuf.Empty
}
var file_task_proto_depIdxs = []int32{
	34, // 0: swarm.v1.CreateTaskRequest.agent_type:type_name -> swarm.v1.AgentType
	26, // 1: swarm.v1.CreateTaskRequest.input:type_name -> swarm.v1.CreateTaskRequest.InputEntry
	27, // 2: swarm.v1.CreateTaskRequest.metadata:type_name -> swarm.v1.CreateTaskRequest.MetadataEntry
	35, // 3: swarm.v1.CreateTaskRequest.kind:type_name -> swarm.v1.TaskKind
	21, // 4: swarm.v1.CreateTaskResponse.task:type_name -> swarm.v1.Task
	21, // 5: swarm.v1.GetTaskResponse.task:type_name -> swarm.v1.Task
	36, // 6: swarm.v1.ListTasksRequest.status:type_name -> swarm.v1.TaskStatus
	34, // 7: swarm.v1.ListTasksRequest.agent_type:type_name -> swarm.v1.AgentType
	37, // 8: swarm.v1.ListTasksRequest.created_after:type_name -> google.protobuf.Timestamp
	37, // 9: swarm.v1.ListTasksRequest.created_before:type_name -> google.protobuf.Timestamp
	21, // 10: swarm.v1.ListTasksResponse.tasks:type_name -> swarm.v1.Task
	28, // 11: swarm.v1.UpdateTaskRequest.input:type_name -> swarm.v1.UpdateTaskRequest.InputEntry
	29, // 12: swarm.v1.UpdateTaskRequest.metadata:type_name -> swarm.v1.UpdateTaskRequest.MetadataEntry
	21, // 13: swarm.v1.UpdateTaskResponse.task:type_name -> swarm.v1.Task
	22, // 14: swarm.v1.ExecuteTaskResponse.result:type_name -> swarm.v1.TaskResult
	21, // 15: swarm.v1.CancelTaskResponse.task:type_name -> swarm.v1.Task
	21, // 16: swarm.v1.RetryTaskResponse.task:type_name -> swarm.v1.Task
	25, // 17: swarm.v1.ListTaskDependenciesResponse.dependencies:type_name -> swarm.v1.TaskDependency
	36, // 18: swarm.v1.TaskUpdate.status:type_name -> swarm.v1.TaskStatus
	37, // 19: swarm.v1.TaskUpdate.timestamp:type_name -> google.protobuf.Timestamp
	37, // 20: swarm.v1.TaskProgressUpdate.timestamp:type_name -> google.protobuf.Timestamp
	36, // 21: swarm.v1.Task.status:type_name -> swarm.v1.TaskStatus
	35, // 22: swarm.v1.Task.kind:type_name -> swarm.v1.TaskKind
	34, // 23: swarm.v1.Task.agent_type:type_name -> swarm.v1.AgentType
	30, // 24: swarm.v1.Task.input:type_name -> swarm.v1.Task.InputEntry
	31, // 25: swarm.v1.Task.output:type_name -> swarm.v1.Task.OutputEntry
	37, // 26: swarm.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	37, // 27: swarm.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	37, // 28: swarm.v1.Task.started_at:type_name -> google.protobuf.Timestamp
	37, // 29: swarm.v1.Task.completed_at:type_name -> google.protobuf.Timestamp
	22, // 30: swarm.v1.Task.result:type_name -> swarm.v1.TaskResult
	32, // 31: swarm.v1.Task.metadata:type_name -> swarm.v1.Task.MetadataEntry
	24, // 32: swarm.v1.TaskResult.artifacts:type_name -> swarm.v1.Artifact
	23, // 33: swarm.v1.TaskResult.metrics:type_name -> swarm.v1.TaskMetrics
	37, // 34: swarm.v1.TaskResult.completed_at:type_name -> google.protobuf.Timestamp
	37, // 35: swarm.v1.TaskMetrics.start_time:type_name -> google.protobuf.Timestamp
	37, // 36: swarm.v1.TaskMetrics.end_time:type_name -> google.protobuf.Timestamp
	33, // 37: swarm.v1.Artifact.metadata:type_name -> swarm.v1.Artifact.MetadataEntry
	37, // 38: swarm.v1.Artifact.created_at:type_name -> google.protobuf.Timestamp
	0,  // 39: swarm.v1.TaskService.CreateTask:input_type -> swarm.v1.CreateTaskRequest
	2,  // 40: swarm.v1.TaskService.GetTask:input_type -> swarm.v1.GetTaskRequest
	4,  // 41: swarm.v1.TaskService.ListTasks:input_type -> swarm.v1.ListTasksRequest
	6,  // 42: swarm.v1.TaskService.UpdateTask:input_type -> swarm.v1.UpdateTaskRequest
	8,  // 43: swarm.v1.TaskService.DeleteTask:input_type -> swarm.v1.DeleteTaskRequest
	9,  // 44: swarm.v1.TaskService.ExecuteTask:input_type -> swarm.v1.ExecuteTaskRequest
	11, // 45: swarm.v1.TaskService.CancelTask:input_type -> swarm.v1.CancelTaskRequest
	13, // 46: swarm.v1.TaskService.RetryTask:input_type -> swarm.v1.RetryTaskRequest
	15, // 47: swarm.v1.TaskService.ListTaskDependencies:input_type -> swarm.v1.ListTaskDependenciesRequest
	17, // 48: swarm.v1.TaskService.StreamTaskUpdates:input_type -> swarm.v1.StreamTaskUpdatesRequest
	19, // 49: swarm.v1.TaskService.StreamTaskProgress:input_type -> swarm.v1.StreamTaskProgressRequest
	1,  // 50: swarm.v1.TaskService.CreateTask:output_type -> swarm.v1.CreateTaskResponse
	3,  // 51: swarm.v1.TaskService.GetTask:output_type -> swarm.v1.GetTaskResponse
	5,  // 52: swarm.v1.TaskService.ListTasks:output_type -> swarm.v1.ListTasksResponse
	7,  // 53: swarm.v1.TaskService.UpdateTask:output_type -> swarm.v1.UpdateTaskResponse
	38, // 54: swarm.v1.TaskService.DeleteTask:output_type -> google.protobuf.Empty
	10, // 55: swarm.v1.TaskService.ExecuteTask:output_type -> swarm.v1.ExecuteTaskResponse
	12, // 56: swarm.v1.TaskService.CancelTask:output_type -> swarm.v1.CancelTaskResponse
	14, // 57: swarm.v1.TaskService.RetryTask:output_type -> swarm.v1.RetryTaskResponse
	16, // 58: swarm.v1.TaskService.ListTaskDependencies:output_type -> swarm.v1.ListTaskDependenciesResponse
	18, // 59: swarm.v1.TaskService.StreamTaskUpdates:output_type -> swarm.v1.TaskUpdate
	20, // 60: swarm.v1.TaskService.StreamTaskProgress:output_type -> swarm.v1.TaskProgressUpdate
	50, // [50:61] is the sub-list for method output_type
	39, // [39:50] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
